services:

  proxy:
    image: traefik:3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    networks:
      - traefik-public
      - default

  db:
    restart: "no"
    ports:
      - "5433:5432"

  adminer:
    restart: "no"
    ports:
      - "8081:8080"

  backend:
    restart: "no"
    ports:
      - "8001:8000"
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    volumes:
      - ./backend:/app/backend
      - /app/.venv
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  frontend:
    restart: "no"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: build-stage
      args:
        - VITE_API_URL=http://localhost:8001
        - NODE_ENV=development
    command: bunx --bun vite --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
    labels:
      - traefik.enable=false

  playwright:
    build:
      context: .
      dockerfile: frontend/Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - mailcatcher
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/frontend/blob-report
      - ./frontend/test-results:/app/frontend/test-results
    ports:
      - 9323:9323

networks:
  traefik-public:
    external: false
