// This file is auto-generated by @hey-api/openapi-ts

export type _ShareIn = {
    tag_id: string;
    grantee_id: string;
};

export type AddressCreate = {
    label?: string;
    street?: (string | null);
    extended?: (string | null);
    city?: (string | null);
    region?: (string | null);
    postal_code?: (string | null);
    country?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    contact_id: string;
};

export type AddressPublic = {
    label?: string;
    street?: (string | null);
    extended?: (string | null);
    city?: (string | null);
    region?: (string | null);
    postal_code?: (string | null);
    country?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    id: string;
    contact_id: string;
};

export type AddressUpdate = {
    label?: (string | null);
    street?: (string | null);
    extended?: (string | null);
    city?: (string | null);
    region?: (string | null);
    postal_code?: (string | null);
    country?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type Body_import_export_import_vcard = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContactCreate = {
    first_name: string;
    last_name?: (string | null);
    middle_name?: (string | null);
    prefix?: (string | null);
    suffix?: (string | null);
    nickname?: (string | null);
    company?: (string | null);
    department?: (string | null);
    title?: (string | null);
    birthday?: (string | null);
    notes?: (string | null);
    how_we_met?: (string | null);
    is_favorite?: boolean;
    is_archived?: boolean;
    is_deceased?: boolean;
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    stage?: (string | null);
    tag_ids?: (Array<(string)> | null);
    group_ids?: (Array<(string)> | null);
};

export type ContactFieldCreate = {
    field_type: ContactFieldType;
    label: string;
    value: string;
    is_primary?: boolean;
    sort_order?: number;
    contact_id: string;
};

export type ContactFieldPublic = {
    field_type: ContactFieldType;
    label: string;
    value: string;
    is_primary?: boolean;
    sort_order?: number;
    id: string;
    contact_id: string;
};

export type ContactFieldType = 'email' | 'phone' | 'url' | 'social' | 'im' | 'custom';

export type ContactFieldUpdate = {
    field_type?: (ContactFieldType | null);
    label?: (string | null);
    value?: (string | null);
    is_primary?: (boolean | null);
    sort_order?: (number | null);
};

export type ContactPublic = {
    first_name: string;
    last_name?: (string | null);
    middle_name?: (string | null);
    prefix?: (string | null);
    suffix?: (string | null);
    nickname?: (string | null);
    company?: (string | null);
    department?: (string | null);
    title?: (string | null);
    birthday?: (string | null);
    notes?: (string | null);
    how_we_met?: (string | null);
    is_favorite?: boolean;
    is_archived?: boolean;
    is_deceased?: boolean;
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    stage?: (string | null);
    id: string;
    avatar_url: (string | null);
    last_contacted_at: (string | null);
    created_at: string;
    updated_at: string;
    tags?: Array<TagPublic>;
    groups?: Array<GroupPublic>;
};

export type ContactsPublic = {
    data: Array<ContactPublic>;
    count: number;
};

export type ContactUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    middle_name?: (string | null);
    prefix?: (string | null);
    suffix?: (string | null);
    nickname?: (string | null);
    company?: (string | null);
    department?: (string | null);
    title?: (string | null);
    birthday?: (string | null);
    notes?: (string | null);
    how_we_met?: (string | null);
    is_favorite?: (boolean | null);
    is_archived?: (boolean | null);
    is_deceased?: (boolean | null);
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    stage?: (string | null);
    tag_ids?: (Array<(string)> | null);
    group_ids?: (Array<(string)> | null);
};

export type CustomFieldDefinitionCreate = {
    name: string;
    field_type?: string;
    description?: (string | null);
    options?: (string | null);
    icon?: (string | null);
};

export type CustomFieldDefinitionPublic = {
    name: string;
    field_type?: string;
    description?: (string | null);
    options?: (string | null);
    icon?: (string | null);
    id: string;
    created_at: string;
};

export type CustomFieldDefinitionUpdate = {
    name?: (string | null);
    field_type?: (string | null);
    description?: (string | null);
    options?: (string | null);
    icon?: (string | null);
};

export type CustomFieldValueCreate = {
    value: string;
    contact_id: string;
    field_definition_id: string;
};

export type CustomFieldValuePublic = {
    value: string;
    id: string;
    contact_id: string;
    field_definition_id: string;
    field_name?: (string | null);
};

export type CustomFieldValueUpdate = {
    value?: (string | null);
};

export type DebtCreate = {
    direction: DebtDirection;
    amount: number;
    currency?: string;
    reason?: (string | null);
    is_settled?: boolean;
    settled_at?: (string | null);
    contact_id: string;
};

export type DebtDirection = 'i_owe' | 'they_owe';

export type DebtPublic = {
    direction: DebtDirection;
    amount: number;
    currency?: string;
    reason?: (string | null);
    is_settled?: boolean;
    settled_at?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
};

export type DebtsPublic = {
    data: Array<DebtPublic>;
    count: number;
};

export type DebtUpdate = {
    direction?: (DebtDirection | null);
    amount?: (number | null);
    currency?: (string | null);
    reason?: (string | null);
    is_settled?: (boolean | null);
    settled_at?: (string | null);
};

export type GiftCreate = {
    name: string;
    description?: (string | null);
    status?: GiftStatus;
    occasion?: (string | null);
    gift_date?: (string | null);
    value_amount?: (number | null);
    value_currency?: string;
    url?: (string | null);
    contact_id: string;
};

export type GiftPublic = {
    name: string;
    description?: (string | null);
    status?: GiftStatus;
    occasion?: (string | null);
    gift_date?: (string | null);
    value_amount?: (number | null);
    value_currency?: string;
    url?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
};

export type GiftsPublic = {
    data: Array<GiftPublic>;
    count: number;
};

export type GiftStatus = 'idea' | 'given' | 'received';

export type GiftUpdate = {
    name?: (string | null);
    description?: (string | null);
    status?: (GiftStatus | null);
    occasion?: (string | null);
    gift_date?: (string | null);
    value_amount?: (number | null);
    value_currency?: (string | null);
    url?: (string | null);
};

export type GroupCreate = {
    name: string;
    description?: (string | null);
};

export type GroupPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type GroupsPublic = {
    data: Array<GroupPublic>;
    count: number;
};

export type GroupUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InteractionChannel = 'call' | 'in_person' | 'text' | 'email' | 'video' | 'social' | 'other';

export type InteractionCreate = {
    channel: InteractionChannel;
    occurred_at: string;
    notes?: (string | null);
    mood?: (string | null);
    duration_minutes?: (number | null);
    contact_id: string;
};

export type InteractionPublic = {
    channel: InteractionChannel;
    occurred_at: string;
    notes?: (string | null);
    mood?: (string | null);
    duration_minutes?: (number | null);
    id: string;
    contact_id: string;
    created_at: string;
};

export type InteractionsPublic = {
    data: Array<InteractionPublic>;
    count: number;
};

export type InteractionUpdate = {
    channel?: (InteractionChannel | null);
    occurred_at?: (string | null);
    notes?: (string | null);
    mood?: (string | null);
    duration_minutes?: (number | null);
};

export type JournalEntriesPublic = {
    data: Array<JournalEntryPublic>;
    count: number;
};

export type JournalEntryCreate = {
    body: string;
    mood?: (string | null);
    entry_date: string;
};

export type JournalEntryPublic = {
    body: string;
    mood?: (string | null);
    entry_date: string;
    id: string;
    created_at: string;
    updated_at: string;
};

export type JournalEntryUpdate = {
    body?: (string | null);
    mood?: (string | null);
    entry_date?: (string | null);
};

export type LifeEventCreate = {
    event_type: string;
    title: string;
    description?: (string | null);
    occurred_at: string;
    create_annual_reminder?: boolean;
    contact_id: string;
};

export type LifeEventPublic = {
    event_type: string;
    title: string;
    description?: (string | null);
    occurred_at: string;
    create_annual_reminder?: boolean;
    id: string;
    contact_id: string;
    created_at: string;
};

export type LifeEventsPublic = {
    data: Array<LifeEventPublic>;
    count: number;
};

export type LifeEventUpdate = {
    event_type?: (string | null);
    title?: (string | null);
    description?: (string | null);
    occurred_at?: (string | null);
    create_annual_reminder?: (boolean | null);
};

export type MediaCategory = 'movie' | 'tv_show' | 'podcast' | 'musician' | 'book' | 'other';

export type MediaRecommendationCreate = {
    category: MediaCategory;
    title: string;
    creator?: (string | null);
    note?: (string | null);
    recommended_at?: (string | null);
    contact_id: string;
};

export type MediaRecommendationPublic = {
    category: MediaCategory;
    title: string;
    creator?: (string | null);
    note?: (string | null);
    recommended_at?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type MediaRecommendationsPublic = {
    data: Array<MediaRecommendationPublic>;
    count: number;
};

export type MediaRecommendationUpdate = {
    category?: (MediaCategory | null);
    title?: (string | null);
    creator?: (string | null);
    note?: (string | null);
    recommended_at?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteCreate = {
    body: string;
    contact_id: string;
};

export type NotePublic = {
    body: string;
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type NotesPublic = {
    data: Array<NotePublic>;
    count: number;
};

export type NoteUpdate = {
    body?: (string | null);
};

export type PetCreate = {
    name: string;
    species?: (string | null);
    breed?: (string | null);
    notes?: (string | null);
    contact_id: string;
};

export type PetPublic = {
    name: string;
    species?: (string | null);
    breed?: (string | null);
    notes?: (string | null);
    id: string;
    contact_id: string;
};

export type PetUpdate = {
    name?: (string | null);
    species?: (string | null);
    breed?: (string | null);
    notes?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RelationshipCreate = {
    relationship_type: string;
    relationship_group: RelationshipGroup;
    notes?: (string | null);
    contact_id: string;
    related_contact_id: string;
};

export type RelationshipGroup = 'family' | 'romantic' | 'friend' | 'work' | 'other';

export type RelationshipPublic = {
    relationship_type: string;
    relationship_group: RelationshipGroup;
    notes?: (string | null);
    id: string;
    contact_id: string;
    related_contact_id: string;
};

export type RelationshipUpdate = {
    relationship_type?: (string | null);
    relationship_group?: (RelationshipGroup | null);
    notes?: (string | null);
};

export type ReminderCreate = {
    title: string;
    description?: (string | null);
    remind_at: string;
    frequency?: ReminderFrequency;
    is_active?: boolean;
    contact_id?: (string | null);
};

export type ReminderFrequency = 'once' | 'daily' | 'weekly' | 'monthly' | 'yearly';

export type ReminderPublic = {
    title: string;
    description?: (string | null);
    remind_at: string;
    frequency?: ReminderFrequency;
    is_active?: boolean;
    id: string;
    contact_id: (string | null);
    last_sent_at: (string | null);
    snoozed_until: (string | null);
    created_at: string;
};

export type RemindersPublic = {
    data: Array<ReminderPublic>;
    count: number;
};

export type ReminderUpdate = {
    title?: (string | null);
    description?: (string | null);
    remind_at?: (string | null);
    frequency?: (ReminderFrequency | null);
    is_active?: (boolean | null);
};

export type TagCreate = {
    name: string;
    color?: (string | null);
};

export type TagPublic = {
    name: string;
    color?: (string | null);
    id: string;
    created_at: string;
};

export type TagSharePublic = {
    tag_id: string;
    grantee_id: string;
    grantee_email: string;
    created_at: string;
};

export type TagSharesPublic = {
    data: Array<TagSharePublic>;
    count: number;
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type TagUpdate = {
    name?: (string | null);
    color?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WebhookEndpointBase = {
    name: string;
    url?: (string | null);
    direction: string;
    event_types?: (string | null);
    is_active?: boolean;
    secret?: (string | null);
};

export type AddressesListAddressesData = {
    contactId: string;
};

export type AddressesListAddressesResponse = (unknown);

export type AddressesCreateAddressRouteData = {
    requestBody: AddressCreate;
};

export type AddressesCreateAddressRouteResponse = (AddressPublic);

export type AddressesUpdateAddressData = {
    addressId: string;
    requestBody: AddressUpdate;
};

export type AddressesUpdateAddressResponse = (AddressPublic);

export type AddressesDeleteAddressData = {
    addressId: string;
};

export type AddressesDeleteAddressResponse = (unknown);

export type CarddavWellKnownCarddavResponse = (unknown);

export type ContactFieldsListContactFieldsData = {
    contactId: string;
    limit?: number;
    skip?: number;
};

export type ContactFieldsListContactFieldsResponse = (unknown);

export type ContactFieldsCreateContactFieldRouteData = {
    requestBody: ContactFieldCreate;
};

export type ContactFieldsCreateContactFieldRouteResponse = (ContactFieldPublic);

export type ContactFieldsUpdateContactFieldData = {
    fieldId: string;
    requestBody: ContactFieldUpdate;
};

export type ContactFieldsUpdateContactFieldResponse = (ContactFieldPublic);

export type ContactFieldsDeleteContactFieldData = {
    fieldId: string;
};

export type ContactFieldsDeleteContactFieldResponse = (unknown);

export type ContactsListContactsData = {
    groupId?: (string | null);
    isArchived?: (boolean | null);
    isFavorite?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    stage?: (string | null);
    tagId?: (string | null);
};

export type ContactsListContactsResponse = (ContactsPublic);

export type ContactsCreateContactData = {
    requestBody: ContactCreate;
};

export type ContactsCreateContactResponse = (ContactPublic);

export type ContactsListLosingTouchData = {
    limit?: number;
};

export type ContactsListLosingTouchResponse = (ContactsPublic);

export type ContactsGetContactData = {
    contactId: string;
};

export type ContactsGetContactResponse = (ContactPublic);

export type ContactsUpdateContactData = {
    contactId: string;
    requestBody: ContactUpdate;
};

export type ContactsUpdateContactResponse = (ContactPublic);

export type ContactsDeleteContactData = {
    contactId: string;
};

export type ContactsDeleteContactResponse = (unknown);

export type CustomFieldsListFieldDefinitionsResponse = (unknown);

export type CustomFieldsCreateFieldDefinitionData = {
    requestBody: CustomFieldDefinitionCreate;
};

export type CustomFieldsCreateFieldDefinitionResponse = (CustomFieldDefinitionPublic);

export type CustomFieldsUpdateFieldDefinitionData = {
    defId: string;
    requestBody: CustomFieldDefinitionUpdate;
};

export type CustomFieldsUpdateFieldDefinitionResponse = (CustomFieldDefinitionPublic);

export type CustomFieldsDeleteFieldDefinitionData = {
    defId: string;
};

export type CustomFieldsDeleteFieldDefinitionResponse = (unknown);

export type CustomFieldsListFieldValuesData = {
    contactId: string;
};

export type CustomFieldsListFieldValuesResponse = (unknown);

export type CustomFieldsCreateFieldValueData = {
    requestBody: CustomFieldValueCreate;
};

export type CustomFieldsCreateFieldValueResponse = (CustomFieldValuePublic);

export type CustomFieldsUpdateFieldValueData = {
    requestBody: CustomFieldValueUpdate;
    valueId: string;
};

export type CustomFieldsUpdateFieldValueResponse = (CustomFieldValuePublic);

export type CustomFieldsDeleteFieldValueData = {
    valueId: string;
};

export type CustomFieldsDeleteFieldValueResponse = (unknown);

export type DebtsListDebtsData = {
    contactId: string;
};

export type DebtsListDebtsResponse = (DebtsPublic);

export type DebtsCreateDebtRouteData = {
    requestBody: DebtCreate;
};

export type DebtsCreateDebtRouteResponse = (DebtPublic);

export type DebtsUpdateDebtData = {
    debtId: string;
    requestBody: DebtUpdate;
};

export type DebtsUpdateDebtResponse = (DebtPublic);

export type DebtsDeleteDebtData = {
    debtId: string;
};

export type DebtsDeleteDebtResponse = (unknown);

export type GiftsListGiftsData = {
    contactId: string;
};

export type GiftsListGiftsResponse = (GiftsPublic);

export type GiftsCreateGiftRouteData = {
    requestBody: GiftCreate;
};

export type GiftsCreateGiftRouteResponse = (GiftPublic);

export type GiftsUpdateGiftData = {
    giftId: string;
    requestBody: GiftUpdate;
};

export type GiftsUpdateGiftResponse = (GiftPublic);

export type GiftsDeleteGiftData = {
    giftId: string;
};

export type GiftsDeleteGiftResponse = (unknown);

export type GroupsListGroupsData = {
    limit?: number;
    skip?: number;
};

export type GroupsListGroupsResponse = (GroupsPublic);

export type GroupsCreateGroupRouteData = {
    requestBody: GroupCreate;
};

export type GroupsCreateGroupRouteResponse = (GroupPublic);

export type GroupsUpdateGroupData = {
    groupId: string;
    requestBody: GroupUpdate;
};

export type GroupsUpdateGroupResponse = (GroupPublic);

export type GroupsDeleteGroupData = {
    groupId: string;
};

export type GroupsDeleteGroupResponse = (unknown);

export type ImportExportImportVcardData = {
    formData: Body_import_export_import_vcard;
};

export type ImportExportImportVcardResponse = (unknown);

export type ImportExportExportVcardResponse = (unknown);

export type ImportExportExportJsonResponse = (unknown);

export type InteractionsListInteractionsData = {
    contactId?: (string | null);
    limit?: number;
    skip?: number;
};

export type InteractionsListInteractionsResponse = (InteractionsPublic);

export type InteractionsCreateInteractionRouteData = {
    requestBody: InteractionCreate;
};

export type InteractionsCreateInteractionRouteResponse = (InteractionPublic);

export type InteractionsUpdateInteractionData = {
    interactionId: string;
    requestBody: InteractionUpdate;
};

export type InteractionsUpdateInteractionResponse = (InteractionPublic);

export type InteractionsDeleteInteractionData = {
    interactionId: string;
};

export type InteractionsDeleteInteractionResponse = (unknown);

export type JournalListJournalEntriesData = {
    limit?: number;
    skip?: number;
};

export type JournalListJournalEntriesResponse = (JournalEntriesPublic);

export type JournalCreateJournalEntryRouteData = {
    requestBody: JournalEntryCreate;
};

export type JournalCreateJournalEntryRouteResponse = (JournalEntryPublic);

export type JournalUpdateJournalEntryData = {
    entryId: string;
    requestBody: JournalEntryUpdate;
};

export type JournalUpdateJournalEntryResponse = (JournalEntryPublic);

export type JournalDeleteJournalEntryData = {
    entryId: string;
};

export type JournalDeleteJournalEntryResponse = (unknown);

export type LifeEventsListLifeEventsData = {
    contactId: string;
};

export type LifeEventsListLifeEventsResponse = (LifeEventsPublic);

export type LifeEventsCreateLifeEventRouteData = {
    requestBody: LifeEventCreate;
};

export type LifeEventsCreateLifeEventRouteResponse = (LifeEventPublic);

export type LifeEventsUpdateLifeEventData = {
    eventId: string;
    requestBody: LifeEventUpdate;
};

export type LifeEventsUpdateLifeEventResponse = (LifeEventPublic);

export type LifeEventsDeleteLifeEventData = {
    eventId: string;
};

export type LifeEventsDeleteLifeEventResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaRecommendationsListMediaRecommendationsData = {
    contactId: string;
};

export type MediaRecommendationsListMediaRecommendationsResponse = (MediaRecommendationsPublic);

export type MediaRecommendationsCreateMediaRecommendationRouteData = {
    requestBody: MediaRecommendationCreate;
};

export type MediaRecommendationsCreateMediaRecommendationRouteResponse = (MediaRecommendationPublic);

export type MediaRecommendationsUpdateMediaRecommendationData = {
    recId: string;
    requestBody: MediaRecommendationUpdate;
};

export type MediaRecommendationsUpdateMediaRecommendationResponse = (MediaRecommendationPublic);

export type MediaRecommendationsDeleteMediaRecommendationData = {
    recId: string;
};

export type MediaRecommendationsDeleteMediaRecommendationResponse = (unknown);

export type NotesListNotesData = {
    contactId: string;
    limit?: number;
    skip?: number;
};

export type NotesListNotesResponse = (NotesPublic);

export type NotesCreateNoteRouteData = {
    requestBody: NoteCreate;
};

export type NotesCreateNoteRouteResponse = (NotePublic);

export type NotesUpdateNoteData = {
    noteId: string;
    requestBody: NoteUpdate;
};

export type NotesUpdateNoteResponse = (NotePublic);

export type NotesDeleteNoteData = {
    noteId: string;
};

export type NotesDeleteNoteResponse = (unknown);

export type PetsListPetsData = {
    contactId: string;
};

export type PetsListPetsResponse = (unknown);

export type PetsCreatePetRouteData = {
    requestBody: PetCreate;
};

export type PetsCreatePetRouteResponse = (PetPublic);

export type PetsUpdatePetData = {
    petId: string;
    requestBody: PetUpdate;
};

export type PetsUpdatePetResponse = (PetPublic);

export type PetsDeletePetData = {
    petId: string;
};

export type PetsDeletePetResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RelationshipsListRelationshipsData = {
    contactId: string;
};

export type RelationshipsListRelationshipsResponse = (unknown);

export type RelationshipsCreateRelationshipRouteData = {
    requestBody: RelationshipCreate;
};

export type RelationshipsCreateRelationshipRouteResponse = (RelationshipPublic);

export type RelationshipsUpdateRelationshipData = {
    relId: string;
    requestBody: RelationshipUpdate;
};

export type RelationshipsUpdateRelationshipResponse = (RelationshipPublic);

export type RelationshipsDeleteRelationshipData = {
    relId: string;
};

export type RelationshipsDeleteRelationshipResponse = (unknown);

export type RemindersListRemindersData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RemindersListRemindersResponse = (RemindersPublic);

export type RemindersCreateReminderRouteData = {
    requestBody: ReminderCreate;
};

export type RemindersCreateReminderRouteResponse = (ReminderPublic);

export type RemindersUpdateReminderData = {
    reminderId: string;
    requestBody: ReminderUpdate;
};

export type RemindersUpdateReminderResponse = (ReminderPublic);

export type RemindersDeleteReminderData = {
    reminderId: string;
};

export type RemindersDeleteReminderResponse = (unknown);

export type RemindersSnoozeReminderData = {
    minutes?: number;
    reminderId: string;
};

export type RemindersSnoozeReminderResponse = (unknown);

export type TagsListTagsData = {
    limit?: number;
    skip?: number;
};

export type TagsListTagsResponse = (TagsPublic);

export type TagsCreateTagRouteData = {
    requestBody: TagCreate;
};

export type TagsCreateTagRouteResponse = (TagPublic);

export type TagsUpdateTagData = {
    requestBody: TagUpdate;
    tagId: string;
};

export type TagsUpdateTagResponse = (TagPublic);

export type TagsDeleteTagData = {
    tagId: string;
};

export type TagsDeleteTagResponse = (unknown);

export type TagSharesCreateTagShareData = {
    requestBody: _ShareIn;
};

export type TagSharesCreateTagShareResponse = (TagSharePublic);

export type TagSharesListTagSharesData = {
    tagId: string;
};

export type TagSharesListTagSharesResponse = (TagSharesPublic);

export type TagSharesDeleteTagShareData = {
    granteeId: string;
    tagId: string;
};

export type TagSharesDeleteTagShareResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebhooksListWebhooksResponse = (unknown);

export type WebhooksCreateWebhookData = {
    requestBody: WebhookEndpointBase;
};

export type WebhooksCreateWebhookResponse = (unknown);

export type WebhooksUpdateWebhookData = {
    requestBody: WebhookEndpointBase;
    webhookId: string;
};

export type WebhooksUpdateWebhookResponse = (unknown);

export type WebhooksDeleteWebhookData = {
    webhookId: string;
};

export type WebhooksDeleteWebhookResponse = (unknown);

export type WebhooksInboundWebhookData = {
    apiKey: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type WebhooksInboundWebhookResponse = (unknown);