// This file is auto-generated by @hey-api/openapi-ts

export type _MentionSourceContact = {
    id: string;
    first_name: string;
    last_name?: (string | null);
    avatar_url?: (string | null);
};

export type _ShareIn = {
    tag_id: string;
    grantee_id?: (string | null);
    grantee_email?: (string | null);
};

export type ActivityLogPublic = {
    id: string;
    owner_id: string;
    actor_id: (string | null);
    entity_type: string;
    entity_id: string;
    action: string;
    changes_json: ({
    [key: string]: unknown;
} | null);
    occurred_at: string;
};

export type ActivityLogsPublic = {
    data: Array<ActivityLogPublic>;
    count: number;
};

export type AddressCreate = {
    /**
     * Label like "home", "work", "other".
     */
    label?: string;
    /**
     * Street line 1.
     */
    street?: (string | null);
    /**
     * Apartment, suite, floor, etc.
     */
    extended?: (string | null);
    /**
     * City.
     */
    city?: (string | null);
    /**
     * State, province, or region.
     */
    region?: (string | null);
    /**
     * ZIP or postal code.
     */
    postal_code?: (string | null);
    /**
     * Country.
     */
    country?: (string | null);
    /**
     * Geocoded latitude; used for map visualization.
     */
    latitude?: (number | null);
    /**
     * Geocoded longitude; used for map visualization.
     */
    longitude?: (number | null);
    contact_id: string;
};

export type AddressesPublic = {
    data: Array<AddressPublic>;
    count: number;
};

export type AddressPublic = {
    /**
     * Label like "home", "work", "other".
     */
    label?: string;
    /**
     * Street line 1.
     */
    street?: (string | null);
    /**
     * Apartment, suite, floor, etc.
     */
    extended?: (string | null);
    /**
     * City.
     */
    city?: (string | null);
    /**
     * State, province, or region.
     */
    region?: (string | null);
    /**
     * ZIP or postal code.
     */
    postal_code?: (string | null);
    /**
     * Country.
     */
    country?: (string | null);
    /**
     * Geocoded latitude; used for map visualization.
     */
    latitude?: (number | null);
    /**
     * Geocoded longitude; used for map visualization.
     */
    longitude?: (number | null);
    id: string;
    contact_id: string;
};

export type AddressUpdate = {
    label?: (string | null);
    street?: (string | null);
    extended?: (string | null);
    city?: (string | null);
    region?: (string | null);
    postal_code?: (string | null);
    country?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type APIKeyCreate = {
    name: string;
    can_impersonate?: Array<(string)>;
    expires_at?: (string | null);
};

/**
 * Returned once at creation — plaintext_key is never stored.
 */
export type APIKeyCreated = {
    id: string;
    name: string;
    key_prefix: string;
    owned_by_user_id: string;
    can_impersonate: Array<(string)>;
    created_at: string;
    last_used_at: (string | null);
    revoked_at: (string | null);
    expires_at: (string | null);
    plaintext_key: string;
};

export type APIKeyPublic = {
    id: string;
    name: string;
    key_prefix: string;
    owned_by_user_id: string;
    can_impersonate: Array<(string)>;
    created_at: string;
    last_used_at: (string | null);
    revoked_at: (string | null);
    expires_at: (string | null);
};

export type APIKeysPublic = {
    data: Array<APIKeyPublic>;
    count: number;
};

/**
 * Response model for avatar upload.
 */
export type AvatarUploadResponse = {
    avatar_url: string;
};

export type Body_contacts_upload_avatar_file = {
    file: (Blob | File);
};

export type Body_ical_upload_ical = {
    file: (Blob | File);
};

export type Body_import_export_import_csv = {
    file: (Blob | File);
    column_mapping?: ({
    [key: string]: (string | null);
} | null);
};

export type Body_import_export_import_vcard = {
    file: (Blob | File);
};

export type Body_import_export_preview_csv_import = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Filter criteria matching list_contacts parameters.
 */
export type BulkContactFilter = {
    search?: (string | null);
    tag_id?: (string | null);
    is_favorite?: (boolean | null);
    is_archived?: (boolean | null);
    stage?: (string | null);
};

/**
 * A single operation to apply to matching contacts.
 */
export type BulkContactOperation = {
    add_tag_ids?: (Array<(string)> | null);
    remove_tag_ids?: (Array<(string)> | null);
    set_is_archived?: (boolean | null);
    set_is_favorite?: (boolean | null);
};

/**
 * Bulk operation request body.
 */
export type BulkContactRequest = {
    contact_ids?: (Array<(string)> | null);
    select_all_filtered?: boolean;
    filters?: (BulkContactFilter | null);
    limit?: number;
    operations: BulkContactOperation;
};

/**
 * Bulk operation result.
 */
export type BulkContactResult = {
    updated_count: number;
    skipped_count: number;
    failed_ids?: Array<(string)>;
};

export type CalendarEntry = {
    contact_id: string;
    name: string;
    type: string;
    age: (number | null);
};

export type CalendarMonthResponse = {
    month: string;
    days: {
        [key: string]: Array<CalendarEntry>;
    };
};

export type CommunicationPreferencePublic = {
    /**
     * Preferred contact channel (call, in_person, text, email, video, social, other).
     */
    preferred_channel?: (string | null);
    /**
     * Preferred contact time window in HH:MM-HH:MM format, local to the contact.
     */
    best_time_local?: (string | null);
    /**
     * When True, suppress all outbound contact reminders.
     */
    do_not_contact?: boolean;
    /**
     * Reason for do-not-contact status (e.g. deceased, requested removal).
     */
    do_not_contact_reason?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type CommunicationPreferenceUpdate = {
    preferred_channel?: (string | null);
    best_time_local?: (string | null);
    do_not_contact?: (boolean | null);
    do_not_contact_reason?: (string | null);
};

export type ContactCreate = {
    /**
     * Given name; required.
     */
    first_name: string;
    /**
     * Family name.
     */
    last_name?: (string | null);
    /**
     * Middle name or initial.
     */
    middle_name?: (string | null);
    /**
     * Honorific like Dr., Mr., Ms.
     */
    prefix?: (string | null);
    /**
     * Suffix like Jr., PhD.
     */
    suffix?: (string | null);
    /**
     * Preferred or informal name.
     */
    nickname?: (string | null);
    /**
     * Organization name.
     */
    company?: (string | null);
    /**
     * Department within the company.
     */
    department?: (string | null);
    /**
     * Job title.
     */
    title?: (string | null);
    /**
     * Date of birth; used for milestone and birthday reminders.
     */
    birthday?: (string | null);
    /**
     * Short story of how the introduction happened.
     */
    how_we_met?: (string | null);
    /**
     * Pinned to the top of contact lists.
     */
    is_favorite?: boolean;
    /**
     * Soft-deleted; excluded from default lists.
     */
    is_archived?: boolean;
    /**
     * Marks the contact as deceased.
     */
    is_deceased?: boolean;
    /**
     * Date the contact passed away.
     */
    deceased_at?: (string | null);
    /**
     * Target days between interactions; drives losing-touch cadence.
     */
    contact_frequency_days?: (number | null);
    /**
     * If True, suppress all contact reminders and actions for this contact.
     */
    do_not_contact?: boolean;
    /**
     * Optional reason why the contact was marked do-not-contact.
     */
    do_not_contact_reason?: (string | null);
    /**
     * Kanban stage like Active, Dormant, Lost.
     */
    stage?: (string | null);
    /**
     * Source system that created this contact.
     */
    source?: ContactSource;
    /**
     * External ID from the source system (e.g. Google contact ID, CardDAV UID).
     */
    source_external_id?: (string | null);
    tag_ids?: (Array<(string)> | null);
};

export type ContactFieldCreate = {
    /**
     * Kind of contact info (email or phone).
     */
    field_type: ContactFieldType;
    /**
     * Label like "home", "work", "cell", "twitter".
     */
    label: string;
    /**
     * The actual email address, phone number, etc.
     */
    value: string;
    /**
     * Marks the primary entry for this field_type on the contact.
     */
    is_primary?: boolean;
    /**
     * Display order within the same field_type.
     */
    sort_order?: number;
    contact_id: string;
};

export type ContactFieldPublic = {
    /**
     * Kind of contact info (email or phone).
     */
    field_type: ContactFieldType;
    /**
     * Label like "home", "work", "cell", "twitter".
     */
    label: string;
    /**
     * The actual email address, phone number, etc.
     */
    value: string;
    /**
     * Marks the primary entry for this field_type on the contact.
     */
    is_primary?: boolean;
    /**
     * Display order within the same field_type.
     */
    sort_order?: number;
    id: string;
    contact_id: string;
};

export type ContactFieldsPublic = {
    data: Array<ContactFieldPublic>;
    count: number;
};

export type ContactFieldType = 'email' | 'phone';

export type ContactFieldUpdate = {
    field_type?: (ContactFieldType | null);
    label?: (string | null);
    value?: (string | null);
    is_primary?: (boolean | null);
    sort_order?: (number | null);
};

/**
 * A geo point representing a contact's address.
 */
export type ContactGeoPoint = {
    contact_id: string;
    contact_name: string;
    avatar_url?: (string | null);
    latitude: number;
    longitude: number;
    address_label: string;
    city?: (string | null);
    country?: (string | null);
    street?: (string | null);
};

/**
 * 52-week interaction heatmap for a contact.
 */
export type ContactHeatmap = {
    data: Array<WeekBucket>;
};

export type ContactPublic = {
    /**
     * Given name; required.
     */
    first_name: string;
    /**
     * Family name.
     */
    last_name?: (string | null);
    /**
     * Middle name or initial.
     */
    middle_name?: (string | null);
    /**
     * Honorific like Dr., Mr., Ms.
     */
    prefix?: (string | null);
    /**
     * Suffix like Jr., PhD.
     */
    suffix?: (string | null);
    /**
     * Preferred or informal name.
     */
    nickname?: (string | null);
    /**
     * Organization name.
     */
    company?: (string | null);
    /**
     * Department within the company.
     */
    department?: (string | null);
    /**
     * Job title.
     */
    title?: (string | null);
    /**
     * Date of birth; used for milestone and birthday reminders.
     */
    birthday?: (string | null);
    /**
     * Short story of how the introduction happened.
     */
    how_we_met?: (string | null);
    /**
     * Pinned to the top of contact lists.
     */
    is_favorite?: boolean;
    /**
     * Soft-deleted; excluded from default lists.
     */
    is_archived?: boolean;
    /**
     * Marks the contact as deceased.
     */
    is_deceased?: boolean;
    /**
     * Date the contact passed away.
     */
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    do_not_contact?: boolean;
    do_not_contact_reason?: (string | null);
    /**
     * Kanban stage like Active, Dormant, Lost.
     */
    stage?: (string | null);
    /**
     * Source system that created this contact.
     */
    source?: ContactSource;
    /**
     * External ID from the source system.
     */
    source_external_id?: (string | null);
    id: string;
    avatar_url: (string | null);
    last_contacted_at: (string | null);
    created_at: string;
    updated_at: string;
    deleted_at?: (string | null);
    tags?: Array<TagPublic>;
    groups?: Array<GroupPublic>;
    stage_events?: Array<ContactStageEventPublic>;
};

/**
 * Source system that created a contact.
 */
export type ContactSource = 'manual' | 'vcard_import' | 'carddav' | 'google' | 'webhook';

export type ContactsPublic = {
    data: Array<ContactPublic>;
    count: number;
};

export type ContactStageEventPublic = {
    /**
     * Previous stage value; null when the contact is first assigned a stage.
     */
    old_stage?: (string | null);
    /**
     * New stage value; null when the contact is cleared.
     */
    new_stage?: (string | null);
    /**
     * When the stage change occurred (UTC).
     */
    changed_at?: string;
    id: string;
    contact_id: string;
    owner_id: string;
    changed_by_id: (string | null);
};

export type ContactStageEventsPublic = {
    data: Array<ContactStageEventPublic>;
    count: number;
};

export type ContactUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    middle_name?: (string | null);
    prefix?: (string | null);
    suffix?: (string | null);
    nickname?: (string | null);
    company?: (string | null);
    department?: (string | null);
    title?: (string | null);
    birthday?: (string | null);
    how_we_met?: (string | null);
    is_favorite?: (boolean | null);
    is_archived?: (boolean | null);
    is_deceased?: (boolean | null);
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    stage?: (string | null);
    source?: (ContactSource | null);
    source_external_id?: (string | null);
    do_not_contact?: (boolean | null);
    do_not_contact_reason?: (string | null);
    tag_ids?: (Array<(string)> | null);
};

/**
 * Response for CSV import.
 */
export type CSVImportResponse = {
    imported: number;
    skipped: number;
    updated: number;
    errors: Array<(string)>;
    tag_names_created?: Array<(string)>;
};

/**
 * Preview of CSV import: column mapping and sample rows.
 */
export type CSVPreviewResponse = {
    headers: Array<(string)>;
    detected_mapping: {
        [key: string]: (string | null);
    };
    sample_rows: Array<{
        [key: string]: (string);
    }>;
    total_rows: number;
    encoding: string;
};

export type CustomFieldDefinitionCreate = {
    /**
     * Custom field name shown in the UI.
     */
    name: string;
    /**
     * Field type: text, number, date, boolean, or select.
     */
    field_type?: string;
    /**
     * Help text displayed alongside the field in the UI.
     */
    description?: (string | null);
    /**
     * Comma-separated options for field_type="select".
     */
    options?: (string | null);
    /**
     * Icon slug for the UI (e.g. "heart", "book").
     */
    icon?: (string | null);
};

export type CustomFieldDefinitionPublic = {
    /**
     * Custom field name shown in the UI.
     */
    name: string;
    /**
     * Field type: text, number, date, boolean, or select.
     */
    field_type?: string;
    /**
     * Help text displayed alongside the field in the UI.
     */
    description?: (string | null);
    /**
     * Comma-separated options for field_type="select".
     */
    options?: (string | null);
    /**
     * Icon slug for the UI (e.g. "heart", "book").
     */
    icon?: (string | null);
    id: string;
    created_at: string;
};

export type CustomFieldDefinitionsPublic = {
    data: Array<CustomFieldDefinitionPublic>;
    count: number;
};

export type CustomFieldDefinitionUpdate = {
    name?: (string | null);
    field_type?: (string | null);
    description?: (string | null);
    options?: (string | null);
    icon?: (string | null);
};

export type CustomFieldValueCreate = {
    /**
     * Value as a string; coerced from the declared field_type.
     */
    value: string;
    contact_id: string;
    field_definition_id: string;
};

export type CustomFieldValuePublic = {
    /**
     * Value as a string; coerced from the declared field_type.
     */
    value: string;
    id: string;
    contact_id: string;
    field_definition_id: string;
    field_name?: (string | null);
};

export type CustomFieldValuesPublic = {
    data: Array<CustomFieldValuePublic>;
    count: number;
};

export type CustomFieldValueUpdate = {
    value?: (string | null);
};

export type DebtCreate = {
    /**
     * Who owes whom: i_owe (you owe them) or they_owe (they owe you).
     */
    direction: DebtDirection;
    /**
     * Amount owed; must be greater than zero.
     */
    amount: number;
    /**
     * ISO 4217 currency code.
     */
    currency?: string;
    /**
     * What the debt is for.
     */
    reason?: (string | null);
    /**
     * Date the debt was settled.
     */
    settled_at?: (string | null);
    /**
     * Marked paid off.
     */
    is_settled?: boolean;
    contact_id: string;
};

export type DebtDirection = 'i_owe' | 'they_owe';

export type DebtPaymentCreate = {
    /**
     * Payment amount; must be greater than zero.
     */
    amount: number;
    /**
     * Date the payment was made.
     */
    paid_at: string;
    /**
     * Optional note about the payment.
     */
    note?: (string | null);
};

export type DebtPaymentPublic = {
    /**
     * Payment amount; must be greater than zero.
     */
    amount: number;
    /**
     * Date the payment was made.
     */
    paid_at: string;
    /**
     * Optional note about the payment.
     */
    note?: (string | null);
    id: string;
    created_at: string;
};

export type DebtPublic = {
    /**
     * Who owes whom: i_owe (you owe them) or they_owe (they owe you).
     */
    direction: DebtDirection;
    /**
     * Amount owed; must be greater than zero.
     */
    amount: number;
    /**
     * ISO 4217 currency code.
     */
    currency?: string;
    /**
     * What the debt is for.
     */
    reason?: (string | null);
    /**
     * Date the debt was settled.
     */
    settled_at?: (string | null);
    /**
     * Marked paid off.
     */
    is_settled?: boolean;
    id: string;
    contact_id: string;
    created_at: string;
    deleted_at?: (string | null);
    payments?: Array<DebtPaymentPublic>;
    paid_amount?: (number | null);
};

export type DebtsPublic = {
    data: Array<DebtPublic>;
    count: number;
};

export type DebtUpdate = {
    direction?: (DebtDirection | null);
    amount?: (number | null);
    reason?: (string | null);
    is_settled?: (boolean | null);
    settled_at?: (string | null);
};

export type EmailOAuthTokenPublic = {
    /**
     * OAuth provider name (e.g. 'gmail').
     */
    provider?: string;
    /**
     * The email address these tokens are for.
     */
    email_address: string;
    /**
     * Encrypted access token for the Gmail API.
     */
    encrypted_access_token: string;
    /**
     * Encrypted refresh token for obtaining new access tokens.
     */
    encrypted_refresh_token?: (string | null);
    /**
     * When the access token expires (UTC).
     */
    token_expires_at?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type EmailOAuthTokensPublic = {
    data: Array<EmailOAuthTokenPublic>;
    count: number;
};

export type EnvironmentInfo = {
    environment: string;
};

export type GiftCreate = {
    /**
     * Gift name.
     */
    name: string;
    /**
     * Details about the gift.
     */
    description?: (string | null);
    /**
     * Lifecycle: idea, given, or received.
     */
    status?: GiftStatus;
    /**
     * Occasion like Birthday, Christmas, Housewarming.
     */
    occasion?: (string | null);
    /**
     * When the gift was given or received.
     */
    gift_date?: (string | null);
    /**
     * Monetary cost or value.
     */
    value_amount?: (number | null);
    /**
     * ISO 4217 currency code.
     */
    value_currency?: string;
    /**
     * Link to the product page (e.g. Amazon).
     */
    url?: (string | null);
    contact_id: string;
};

export type GiftKanbanCard = {
    gift: GiftPublic;
    is_overdue: boolean;
    days_until_occasion?: (number | null);
};

export type GiftKanbanColumn = {
    gifts: Array<GiftKanbanCard>;
    count: number;
    total_value: number;
};

export type GiftPublic = {
    /**
     * Gift name.
     */
    name: string;
    /**
     * Details about the gift.
     */
    description?: (string | null);
    /**
     * Lifecycle: idea, given, or received.
     */
    status?: GiftStatus;
    /**
     * Occasion like Birthday, Christmas, Housewarming.
     */
    occasion?: (string | null);
    /**
     * When the gift was given or received.
     */
    gift_date?: (string | null);
    /**
     * Monetary cost or value.
     */
    value_amount?: (number | null);
    /**
     * ISO 4217 currency code.
     */
    value_currency?: string;
    /**
     * Link to the product page (e.g. Amazon).
     */
    url?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
    days_until_occasion?: (number | null);
    contact_birthday?: (string | null);
    contact_first_name?: (string | null);
    contact_last_name?: (string | null);
};

export type GiftsPublic = {
    data: Array<GiftPublic>;
    count: number;
};

export type GiftStatus = 'idea' | 'purchased' | 'wrapped' | 'given' | 'received';

export type GiftUpdate = {
    name?: (string | null);
    description?: (string | null);
    status?: (GiftStatus | null);
    occasion?: (string | null);
    gift_date?: (string | null);
    value_amount?: (number | null);
    value_currency?: (string | null);
    url?: (string | null);
};

/**
 * Single household member entry returned by /contacts/{id}/household.
 */
export type HouseholdMember = {
    id: string;
    first_name: string;
    last_name?: (string | null);
    nickname?: (string | null);
    birthday?: (string | null);
    age?: (number | null);
    avatar_url?: (string | null);
};

/**
 * Household membership wrapper.
 */
export type HouseholdResponse = {
    data: Array<HouseholdMember>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * iMessage profile data from social.json.
 */
export type IMessageProfilePayload = {
    /**
     * E.164 phone or email for stable iMessage identity.
     */
    imessage_id: string;
    /**
     * iMessage relationship type (close_friend, family, etc.).
     */
    relationship_type?: (string | null);
    /**
     * Key events from iMessage.
     */
    key_events?: (Array<(string)> | null);
    /**
     * Topics discussed in messages.
     */
    topics?: (Array<(string)> | null);
    /**
     * Facts about the contact from message analysis.
     */
    facts_about_other?: (string | null);
    /**
     * Pattern notes from iMessage analysis.
     */
    pattern_notes?: (string | null);
    /**
     * Last message timestamp (Unix epoch).
     */
    last_ts?: (number | null);
    /**
     * Total message count.
     */
    message_count?: (number | null);
    /**
     * Hash of profile data for idempotent updates.
     */
    profile_hash?: (string | null);
};

/**
 * Response model for iMessage profile endpoint.
 */
export type IMessageProfileResponse = {
    imessage_id?: (string | null);
    imessage_synced_at?: (string | null);
    imessage_profile?: ({
    [key: string]: unknown;
} | null);
    profile_hash?: (string | null);
};

/**
 * Request body for iMessage sync.
 */
export type IMessageSyncRequest = {
    /**
     * List of iMessage profiles to sync.
     */
    profiles: Array<IMessageProfilePayload>;
    /**
     * Whether to also sync co-mention edges as relationships.
     */
    sync_co_mentions?: boolean;
    /**
     * Co-mention edges from social.json.
     */
    co_mentions?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * Result of iMessage sync operation.
 */
export type IMessageSyncResult = {
    created_count?: number;
    updated_count?: number;
    skipped_count?: number;
    failed_ids?: Array<(string)>;
};

export type InteractionAttendeeSummary = {
    id: string;
    first_name: string;
    last_name?: (string | null);
    avatar_url?: (string | null);
};

export type InteractionChannel = 'call' | 'in_person' | 'text' | 'email' | 'video' | 'social' | 'other' | 'skip';

export type InteractionCreate = {
    /**
     * How the interaction happened (call, in_person, text, etc.).
     */
    channel: InteractionChannel;
    /**
     * When the interaction actually took place.
     */
    occurred_at: string;
    /**
     * Conversation summary, action items, etc.
     */
    notes?: (string | null);
    /**
     * Emoji or keyword capturing the tone.
     */
    mood?: (string | null);
    /**
     * Length of the interaction in minutes.
     */
    duration_minutes?: (number | null);
    location_label?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    /**
     * If True, this interaction is a draft and excluded from engagement metrics.
     */
    is_draft?: boolean;
    /**
     * Origin of the draft (voice_memo, email_suggestion, manual, import).
     */
    draft_source?: (InteractionDraftSource | null);
    /**
     * RFC 2822 Message-ID for deduplication (EMAIL channel only).
     */
    message_id?: (string | null);
    /**
     * Email subject line (EMAIL channel only).
     */
    email_subject?: (string | null);
    /**
     * Email From header (EMAIL channel only).
     */
    email_from?: (string | null);
    /**
     * Email To header (EMAIL channel only).
     */
    email_to?: (string | null);
    /**
     * Email Date header (EMAIL channel only).
     */
    email_date?: (string | null);
    /**
     * Contacts that attended; must have at least one.
     */
    attendee_ids: Array<(string)>;
};

/**
 * Origin of a draft interaction.
 */
export type InteractionDraftSource = 'voice_memo' | 'email_suggestion' | 'manual' | 'import';

export type InteractionPublic = {
    /**
     * How the interaction happened (call, in_person, text, etc.).
     */
    channel: InteractionChannel;
    /**
     * When the interaction actually took place.
     */
    occurred_at: string;
    /**
     * Conversation summary, action items, etc.
     */
    notes?: (string | null);
    /**
     * Emoji or keyword capturing the tone.
     */
    mood?: (string | null);
    /**
     * Length of the interaction in minutes.
     */
    duration_minutes?: (number | null);
    /**
     * Freeform location text like 'Starbucks on 5th', 'their home', 'the park'.
     */
    location_label?: (string | null);
    /**
     * Geocoded latitude; used for map visualization.
     */
    latitude?: (number | null);
    /**
     * Geocoded longitude; used for map visualization.
     */
    longitude?: (number | null);
    is_draft?: boolean;
    draft_source?: (InteractionDraftSource | null);
    /**
     * RFC 2822 Message-ID for deduplication (EMAIL channel only).
     */
    message_id?: (string | null);
    /**
     * Email subject line (EMAIL channel only).
     */
    email_subject?: (string | null);
    /**
     * Email From header (EMAIL channel only).
     */
    email_from?: (string | null);
    /**
     * Email To header (EMAIL channel only).
     */
    email_to?: (string | null);
    /**
     * Email Date header (EMAIL channel only).
     */
    email_date?: (string | null);
    id: string;
    attendees?: Array<InteractionAttendeeSummary>;
    created_at: string;
    deleted_at?: (string | null);
};

export type InteractionsPublic = {
    data: Array<InteractionPublic>;
    count: number;
};

export type InteractionUpdate = {
    channel?: (InteractionChannel | null);
    occurred_at?: (string | null);
    notes?: (string | null);
    mood?: (string | null);
    duration_minutes?: (number | null);
    location_label?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    /**
     * Replace the attendee set; must have at least one if provided.
     */
    attendee_ids?: (Array<(string)> | null);
};

/**
 * Create schema for inverse relationship map.
 */
export type InverseRelationshipMapCreate = {
    /**
     * Forward relationship type (e.g. 'parent').
     */
    relationship_type: string;
    /**
     * Inverse relationship type (e.g. 'child').
     */
    inverse_type: string;
    /**
     * True when both sides use the same type (spouse<->spouse).
     */
    is_symmetric?: boolean;
};

export type InverseRelationshipMapPublic = {
    /**
     * Forward relationship type (e.g. 'parent').
     */
    relationship_type: string;
    /**
     * Inverse relationship type (e.g. 'child').
     */
    inverse_type: string;
    /**
     * True when both sides use the same type (spouse<->spouse).
     */
    is_symmetric?: boolean;
    id: string;
    created_at: string;
};

export type InverseRelationshipMapsPublic = {
    data: Array<InverseRelationshipMapPublic>;
    count: number;
};

/**
 * Update schema - all fields optional.
 */
export type InverseRelationshipMapUpdate = {
    inverse_type?: (string | null);
    is_symmetric?: (boolean | null);
};

export type JournalEntriesPublic = {
    data: Array<JournalEntryPublic>;
    count: number;
};

export type JournalEntryCreate = {
    /**
     * Entry body, 1-50000 chars.
     */
    body: string;
    /**
     * Emoji or keyword capturing the mood.
     */
    mood?: (string | null);
    /**
     * Date the entry is about (may differ from created_at).
     */
    entry_date: string;
    contact_ids?: (Array<(string)> | null);
};

export type JournalEntryPublic = {
    /**
     * Entry body, 1-50000 chars.
     */
    body: string;
    /**
     * Emoji or keyword capturing the mood.
     */
    mood?: (string | null);
    /**
     * Date the entry is about (may differ from created_at).
     */
    entry_date: string;
    id: string;
    created_at: string;
    updated_at: string;
    contact_ids?: Array<(string)>;
};

export type JournalEntryUpdate = {
    body?: (string | null);
    mood?: (string | null);
    entry_date?: (string | null);
    contact_ids?: (Array<(string)> | null);
};

/**
 * JSON export of all contact rows (raw model_dump per contact).
 */
export type JsonExportResponse = {
    contacts: Array<{
        [key: string]: unknown;
    }>;
};

export type LifeEventCreate = {
    /**
     * Kind of milestone: job_change, move, wedding, baby, graduation, birthday, anniversary, etc.
     */
    event_type: string;
    /**
     * Event title.
     */
    title: string;
    /**
     * Extra details about the event.
     */
    description?: (string | null);
    /**
     * Date the event happened.
     */
    occurred_at: string;
    /**
     * If true, auto-create a yearly recurring reminder on this date.
     */
    create_annual_reminder?: boolean;
    contact_id: string;
};

export type LifeEventPublic = {
    /**
     * Kind of milestone: job_change, move, wedding, baby, graduation, birthday, anniversary, etc.
     */
    event_type: string;
    /**
     * Event title.
     */
    title: string;
    /**
     * Extra details about the event.
     */
    description?: (string | null);
    /**
     * Date the event happened.
     */
    occurred_at: string;
    /**
     * If true, auto-create a yearly recurring reminder on this date.
     */
    create_annual_reminder?: boolean;
    id: string;
    contact_id: string;
    created_at: string;
    deleted_at?: (string | null);
};

export type LifeEventsPublic = {
    data: Array<LifeEventPublic>;
    count: number;
};

export type LifeEventUpdate = {
    event_type?: (string | null);
    title?: (string | null);
    description?: (string | null);
    occurred_at?: (string | null);
    create_annual_reminder?: (boolean | null);
};

export type MediaCategory = 'movie' | 'tv_show' | 'podcast' | 'musician' | 'book' | 'other';

export type MediaRecommendationCreate = {
    /**
     * Media category: movie, tv_show, podcast, musician, book, or other.
     */
    category: MediaCategory;
    /**
     * Title of the work.
     */
    title: string;
    /**
     * Author, director, artist, or similar creator.
     */
    creator?: (string | null);
    /**
     * Why it was recommended or personal reaction.
     */
    note?: (string | null);
    /**
     * Date the recommendation was made.
     */
    recommended_at?: (string | null);
    contact_id: string;
};

export type MediaRecommendationPublic = {
    /**
     * Media category: movie, tv_show, podcast, musician, book, or other.
     */
    category: MediaCategory;
    /**
     * Title of the work.
     */
    title: string;
    /**
     * Author, director, artist, or similar creator.
     */
    creator?: (string | null);
    /**
     * Why it was recommended or personal reaction.
     */
    note?: (string | null);
    /**
     * Date the recommendation was made.
     */
    recommended_at?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type MediaRecommendationsPublic = {
    data: Array<MediaRecommendationPublic>;
    count: number;
};

export type MediaRecommendationUpdate = {
    category?: (MediaCategory | null);
    title?: (string | null);
    creator?: (string | null);
    note?: (string | null);
    recommended_at?: (string | null);
};

/**
 * Request body for merging two contacts.
 */
export type MergeContactsRequest = {
    surviving_id: string;
    absorbed_id: string;
    notes?: (string | null);
};

/**
 * Response after a merge operation.
 */
export type MergeResponse = {
    merge_log_id: string;
    surviving_id: string;
    absorbed_id: string;
    merged_at: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteCreate = {
    /**
     * Note body, 1-50000 chars.
     */
    body: string;
    contact_id: string;
    /**
     * Client-generated UUID for idempotent POSTs; optional.
     */
    client_id?: (string | null);
};

export type NoteMentionPublic = {
    note_id: string;
    note_body: string;
    note_created_at: string;
    source_contact: _MentionSourceContact;
};

export type NoteMentionPublic = {
    note_id: string;
    note_body: string;
    note_created_at: string;
    source_contact: _MentionSourceContact;
};

export type NoteMentionPublic = {
    note_id: string;
    note_body: string;
    note_created_at: string;
    source_contact: _MentionSourceContact;
};

export type NotePublic = {
    /**
     * Note body, 1-50000 chars.
     */
    body: string;
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
    deleted_at?: (string | null);
    client_id?: (string | null);
};

export type NotesPublic = {
    data: Array<NotePublic>;
    count: number;
};

export type NoteUpdate = {
    body?: (string | null);
};

export type Ok = {
    ok?: boolean;
};

export type OrganizationCreate = {
    /**
     * Organization name; deduplicated via trimmed/lowercased value per owner.
     */
    name: string;
    /**
     * Domain for auto-linking (e.g., 'acme.com').
     */
    domain?: (string | null);
    /**
     * Industry sector.
     */
    industry?: (string | null);
    /**
     * Freeform notes about the organization.
     */
    notes?: (string | null);
    /**
     * Label for the organization's address (e.g., 'main', 'hq').
     */
    address_label?: string;
    /**
     * Street line 1.
     */
    address_street?: (string | null);
    /**
     * Apartment, suite, floor, etc.
     */
    address_extended?: (string | null);
    /**
     * City.
     */
    address_city?: (string | null);
    /**
     * State, province, or region.
     */
    address_region?: (string | null);
    /**
     * ZIP or postal code.
     */
    address_postal_code?: (string | null);
    /**
     * Country.
     */
    address_country?: (string | null);
    /**
     * Geocoded latitude.
     */
    address_latitude?: (number | null);
    /**
     * Geocoded longitude.
     */
    address_longitude?: (number | null);
};

export type OrganizationPublic = {
    /**
     * Organization name; deduplicated via trimmed/lowercased value per owner.
     */
    name: string;
    /**
     * Domain for auto-linking (e.g., 'acme.com').
     */
    domain?: (string | null);
    /**
     * Industry sector.
     */
    industry?: (string | null);
    /**
     * Freeform notes about the organization.
     */
    notes?: (string | null);
    /**
     * Label for the organization's address (e.g., 'main', 'hq').
     */
    address_label?: string;
    /**
     * Street line 1.
     */
    address_street?: (string | null);
    /**
     * Apartment, suite, floor, etc.
     */
    address_extended?: (string | null);
    /**
     * City.
     */
    address_city?: (string | null);
    /**
     * State, province, or region.
     */
    address_region?: (string | null);
    /**
     * ZIP or postal code.
     */
    address_postal_code?: (string | null);
    /**
     * Country.
     */
    address_country?: (string | null);
    /**
     * Geocoded latitude.
     */
    address_latitude?: (number | null);
    /**
     * Geocoded longitude.
     */
    address_longitude?: (number | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    contact_count?: number;
};

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationUpdate = {
    name?: (string | null);
    domain?: (string | null);
    industry?: (string | null);
    notes?: (string | null);
    address_label?: (string | null);
    address_street?: (string | null);
    address_extended?: (string | null);
    address_city?: (string | null);
    address_region?: (string | null);
    address_postal_code?: (string | null);
    address_country?: (string | null);
    address_latitude?: (number | null);
    address_longitude?: (number | null);
};

export type OverdueContactPublic = {
    /**
     * Given name; required.
     */
    first_name: string;
    /**
     * Family name.
     */
    last_name?: (string | null);
    /**
     * Middle name or initial.
     */
    middle_name?: (string | null);
    /**
     * Honorific like Dr., Mr., Ms.
     */
    prefix?: (string | null);
    /**
     * Suffix like Jr., PhD.
     */
    suffix?: (string | null);
    /**
     * Preferred or informal name.
     */
    nickname?: (string | null);
    /**
     * Organization name.
     */
    company?: (string | null);
    /**
     * Department within the company.
     */
    department?: (string | null);
    /**
     * Job title.
     */
    title?: (string | null);
    /**
     * Date of birth; used for milestone and birthday reminders.
     */
    birthday?: (string | null);
    /**
     * Short story of how the introduction happened.
     */
    how_we_met?: (string | null);
    /**
     * Pinned to the top of contact lists.
     */
    is_favorite?: boolean;
    /**
     * Soft-deleted; excluded from default lists.
     */
    is_archived?: boolean;
    /**
     * Marks the contact as deceased.
     */
    is_deceased?: boolean;
    /**
     * Date the contact passed away.
     */
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    do_not_contact?: boolean;
    do_not_contact_reason?: (string | null);
    /**
     * Kanban stage like Active, Dormant, Lost.
     */
    stage?: (string | null);
    /**
     * Source system that created this contact.
     */
    source?: ContactSource;
    /**
     * External ID from the source system.
     */
    source_external_id?: (string | null);
    id: string;
    avatar_url: (string | null);
    last_contacted_at: (string | null);
    created_at: string;
    updated_at: string;
    deleted_at?: (string | null);
    tags?: Array<TagPublic>;
    groups?: Array<GroupPublic>;
    stage_events?: Array<ContactStageEventPublic>;
    days_overdue?: (number | null);
};

export type OverdueContactsPublic = {
    data: Array<OverdueContactPublic>;
    count: number;
};

export type PetCreate = {
    /**
     * Pet's name.
     */
    name: string;
    /**
     * Species like dog, cat, bird.
     */
    species?: (string | null);
    /**
     * Breed, if known.
     */
    breed?: (string | null);
    /**
     * Freeform notes (e.g. allergies, birthday).
     */
    notes?: (string | null);
    contact_id: string;
};

export type PetPublic = {
    /**
     * Pet's name.
     */
    name: string;
    /**
     * Species like dog, cat, bird.
     */
    species?: (string | null);
    /**
     * Breed, if known.
     */
    breed?: (string | null);
    /**
     * Freeform notes (e.g. allergies, birthday).
     */
    notes?: (string | null);
    id: string;
    contact_id: string;
};

export type PetsPublic = {
    data: Array<PetPublic>;
    count: number;
};

export type PetUpdate = {
    name?: (string | null);
    species?: (string | null);
    breed?: (string | null);
    notes?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RelationshipCreate = {
    /**
     * Kind of relationship: spouse, child, parent, sibling, friend, colleague, etc.
     */
    relationship_type: string;
    /**
     * Additional context about the relationship.
     */
    notes?: (string | null);
    contact_id: string;
    related_contact_id: string;
    /**
     * Type for the auto-created inverse row (e.g. 'parent' for 'child'). Inferred when omitted.
     */
    inverse_relationship_type?: (string | null);
};

export type RelationshipPublic = {
    /**
     * Kind of relationship: spouse, child, parent, sibling, friend, colleague, etc.
     */
    relationship_type: string;
    /**
     * Additional context about the relationship.
     */
    notes?: (string | null);
    id: string;
    contact_id: string;
    related_contact_id: string;
    inverse_id?: (string | null);
};

export type RelationshipsPublic = {
    data: Array<RelationshipPublic>;
    count: number;
};

export type RelationshipUpdate = {
    relationship_type?: (string | null);
    notes?: (string | null);
};

export type ReminderContactSummary = {
    id: string;
    first_name: string;
    last_name?: (string | null);
    nickname?: (string | null);
    avatar_url?: (string | null);
};

export type ReminderCreate = {
    /**
     * Reminder title.
     */
    title: string;
    /**
     * Extra details shown with the reminder.
     */
    description?: (string | null);
    /**
     * When to fire the reminder.
     */
    remind_at: string;
    /**
     * How often the reminder repeats.
     */
    frequency?: ReminderFrequency;
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    contact_id?: (string | null);
};

/**
 * Reminder enriched with the linked contact (if any) for the bell popover.
 */
export type ReminderDuePublic = {
    /**
     * Reminder title.
     */
    title: string;
    /**
     * Extra details shown with the reminder.
     */
    description?: (string | null);
    /**
     * When to fire the reminder.
     */
    remind_at: string;
    /**
     * How often the reminder repeats.
     */
    frequency?: ReminderFrequency;
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    id: string;
    contact_id: (string | null);
    last_sent_at: (string | null);
    snoozed_until: (string | null);
    created_at: string;
    deleted_at?: (string | null);
    contact?: (ReminderContactSummary | null);
};

export type ReminderFrequency = 'once' | 'daily' | 'weekly' | 'monthly' | 'yearly';

export type ReminderPublic = {
    /**
     * Reminder title.
     */
    title: string;
    /**
     * Extra details shown with the reminder.
     */
    description?: (string | null);
    /**
     * When to fire the reminder.
     */
    remind_at: string;
    /**
     * How often the reminder repeats.
     */
    frequency?: ReminderFrequency;
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    id: string;
    contact_id: (string | null);
    last_sent_at: (string | null);
    snoozed_until: (string | null);
    created_at: string;
    deleted_at?: (string | null);
};

export type RemindersDuePublic = {
    data: Array<ReminderDuePublic>;
    count: number;
};

/**
 * Single snooze history row returned by GET /reminders/{id}/snooze-history.
 */
export type ReminderSnoozeHistoryEntry = {
    snoozed_at: string;
    snoozed_until: string;
    reason?: (string | null);
};

export type ReminderSnoozeRequest = {
    /**
     * Absolute time to snooze until (UTC). Mutually exclusive with minutes.
     */
    snoozed_until?: (string | null);
    /**
     * Minutes from now to snooze for. Mutually exclusive with snoozed_until.
     */
    minutes?: (number | null);
};

/**
 * Aggregate snooze count for a reminder.
 */
export type ReminderSnoozeStat = {
    reminder_id: string;
    snooze_count: number;
};

export type RemindersPublic = {
    data: Array<ReminderPublic>;
    count: number;
};

export type ReminderUpdate = {
    title?: (string | null);
    description?: (string | null);
    remind_at?: (string | null);
    frequency?: (ReminderFrequency | null);
    is_active?: (boolean | null);
};

export type SavedFilterCreate = {
    /**
     * User-visible name for the smart list.
     */
    name: string;
    /**
     * Structured filter: {conditions: FilterCondition[], op: 'and'|'or'}.
     */
    filter_json: {
        [key: string]: unknown;
    };
    /**
     * Optional tag; if set, filter is shared with users who have TagShare access.
     */
    tag_id?: (string | null);
};

export type SavedFilterPublic = {
    /**
     * User-visible name for the smart list.
     */
    name: string;
    /**
     * Structured filter: {conditions: FilterCondition[], op: 'and'|'or'}.
     */
    filter_json: {
        [key: string]: unknown;
    };
    /**
     * Optional tag; if set, filter is shared with users who have TagShare access.
     */
    tag_id?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type SavedFiltersPublic = {
    data: Array<SavedFilterPublic>;
    count: number;
};

export type SavedFilterUpdate = {
    name?: (string | null);
    filter_json?: ({
    [key: string]: unknown;
} | null);
    tag_id?: (string | null);
};

/**
 * Search results grouped by type with total counts.
 */
export type SearchResponse = {
    results: Array<SearchResultItem>;
    total: number;
    query: string;
};

/**
 * A single search result with type discriminator and ranking info.
 */
export type SearchResultItem = {
    id: string;
    type: string;
    title: string;
    snippet?: (string | null);
    rank?: (number | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SetupSubmit = {
    token: string;
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Preview counts for a single entity type.
 */
export type SharePreviewEntity = {
    entity_type: string;
    count: number;
};

export type TagCreate = {
    /**
     * Tag name, 1-100 chars.
     */
    name: string;
    /**
     * Optional hex color like #ff0000 for UI display.
     */
    color?: (string | null);
    /**
     * Optional tag description.
     */
    description?: (string | null);
};

export type TagPublic = {
    /**
     * Tag name, 1-100 chars.
     */
    name: string;
    /**
     * Optional hex color like #ff0000 for UI display.
     */
    color?: (string | null);
    /**
     * Optional tag description.
     */
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Preview of what will be shared when granting access to a tag.
 */
export type TagSharePreview = {
    tag_id: string;
    tag_name: string;
    contact_count: number;
    sample_contacts: Array<(string)>;
    entities: Array<SharePreviewEntity>;
    total_related_rows: number;
};

export type TagSharePublic = {
    tag_id: string;
    grantee_id: string;
    grantee_email: string;
    created_at: string;
};

export type TagSharesPublic = {
    data: Array<TagSharePublic>;
    count: number;
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type TagUpdate = {
    name?: (string | null);
    color?: (string | null);
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    /**
     * Login email; must be unique.
     */
    email: string;
    /**
     * Whether the account can log in.
     */
    is_active?: boolean;
    /**
     * Grants admin-only endpoints.
     */
    is_superuser?: boolean;
    /**
     * Display name; optional.
     */
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    /**
     * Login email; must be unique.
     */
    email: string;
    /**
     * Whether the account can log in.
     */
    is_active?: boolean;
    /**
     * Grants admin-only endpoints.
     */
    is_superuser?: boolean;
    /**
     * Display name; optional.
     */
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    /**
     * Whether the account can log in.
     */
    is_active?: boolean;
    /**
     * Grants admin-only endpoints.
     */
    is_superuser?: boolean;
    /**
     * Display name; optional.
     */
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Public schema for returning conflict data to the API.
 */
export type VCardConflictPublic = {
    /**
     * The contact that has a conflict.
     */
    contact_id: string;
    incoming_vcard_raw: string;
    /**
     * SHA-256 hash of the incoming normalized vCard.
     */
    incoming_hash: string;
    /**
     * SHA-256 hash of the locally-stored normalized vCard at time of conflict.
     */
    local_hash: string;
    /**
     * When the conflict was resolved; None means pending.
     */
    resolved_at?: (string | null);
    /**
     * How the conflict was resolved: 'keep_local', 'accept_remote', 'manual_merge'.
     */
    resolution_type?: (string | null);
    id: string;
    created_at: string;
    /**
     * The locally-stored vCard at time of conflict.
     */
    local_vcard_raw?: (string | null);
};

/**
 * Paginated response for listing conflicts.
 */
export type VCardConflictsPublic = {
    data: Array<VCardConflictPublic>;
    count: number;
};

/**
 * Result of a vCard bulk import.
 */
export type VCardImportResponse = {
    imported: number;
    errors?: Array<(string)>;
};

export type WebhookEndpointBase = {
    /**
     * Human-readable endpoint name.
     */
    name: string;
    /**
     * Target URL for outbound webhooks; null for inbound.
     */
    url?: (string | null);
    /**
     * "inbound" or "outbound".
     */
    direction: string;
    /**
     * Comma-separated event types (e.g. contact.created,interaction.logged).
     */
    event_types?: (string | null);
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    /**
     * HMAC secret for verifying inbound payloads.
     */
    secret?: (string | null);
};

/**
 * Returned once on creation; includes the plaintext api_key.
 */
export type WebhookEndpointCreated = {
    id: string;
    name: string;
    url?: (string | null);
    direction: string;
    event_types?: (string | null);
    is_active: boolean;
    created_at: string;
    api_key: string;
};

/**
 * Public representation of a webhook endpoint (without api_key).
 */
export type WebhookEndpointPublic = {
    id: string;
    name: string;
    url?: (string | null);
    direction: string;
    event_types?: (string | null);
    is_active: boolean;
    created_at: string;
};

export type WebhookEndpointsPublic = {
    data: Array<WebhookEndpointPublic>;
    count: number;
};

/**
 * Generic response shape for inbound/twilio webhook handlers.
 *
 * Fields are optional because different code paths return different subsets
 * (e.g. unmatched contact vs successful interaction).
 */
export type WebhookEventResponse = {
    received?: boolean;
    matched?: (boolean | null);
    channel?: (string | null);
    call_status?: (string | null);
    contact_id?: (string | null);
    interaction_id?: (string | null);
    error?: (string | null);
};

/**
 * A single week bucket for the interaction heatmap.
 */
export type WeekBucket = {
    week_start: string;
    count: number;
};

export type ActivityLogsListActivityLogsData = {
    entityId?: (string | null);
    entityType?: (string | null);
    limit?: number;
    offset?: number;
    tagId?: (string | null);
};

export type ActivityLogsListActivityLogsResponse = (ActivityLogsPublic);

export type AddressesListAddressesData = {
    contactId: string;
};

export type AddressesListAddressesResponse = (AddressesPublic);

export type AddressesCreateAddressRouteData = {
    requestBody: AddressCreate;
};

export type AddressesCreateAddressRouteResponse = (AddressPublic);

export type AddressesUpdateAddressData = {
    addressId: string;
    requestBody: AddressUpdate;
};

export type AddressesUpdateAddressResponse = (AddressPublic);

export type AddressesDeleteAddressData = {
    addressId: string;
};

export type AddressesDeleteAddressResponse = (Ok);

export type AddressesGeocodeAddressManualData = {
    addressId: string;
};

export type AddressesGeocodeAddressManualResponse = (AddressPublic);

export type AddressesGeocodeMissingCoordinatesResponse = ({
    [key: string]: unknown;
});

export type ApiKeysListMyApiKeysResponse = (APIKeysPublic);

export type ApiKeysCreateMyApiKeyData = {
    requestBody: APIKeyCreate;
};

export type ApiKeysCreateMyApiKeyResponse = (APIKeyCreated);

export type ApiKeysRevokeMyApiKeyData = {
    apiKeyId: string;
};

export type ApiKeysRevokeMyApiKeyResponse = (Message);

export type CalendarGetCalendarMonthData = {
    yyyyMm: string;
};

export type CalendarGetCalendarMonthResponse = (CalendarMonthResponse);

export type CalendarCreateCalendarTokenData = {
    requestBody: CalendarTokenCreate;
};

export type CalendarCreateCalendarTokenResponse = (CalendarTokenPublic);

export type CalendarListCalendarTokensResponse = (CalendarTokensPublic);

export type CalendarRevokeCalendarTokenData = {
    tokenId: string;
};

export type CalendarRevokeCalendarTokenResponse = (unknown);

export type CalendarGetCalendarIcsData = {
    /**
     * Optional timezone for output (e.g., America/Chicago)
     */
    tz?: (string | null);
};

export type CalendarGetCalendarIcsResponse = (unknown);

export type CarddavWellKnownCarddavResponse = (unknown);

export type CommunicationPreferencesGetCommunicationPreferenceData = {
    contactId: string;
};

export type CommunicationPreferencesGetCommunicationPreferenceResponse = ((CommunicationPreferencePublic | null));

export type CommunicationPreferencesUpsertCommunicationPreferenceData = {
    contactId: string;
    requestBody: CommunicationPreferenceUpdate;
};

export type CommunicationPreferencesUpsertCommunicationPreferenceResponse = (CommunicationPreferencePublic);

export type CommunicationPreferencesDeleteCommunicationPreferenceData = {
    contactId: string;
};

export type CommunicationPreferencesDeleteCommunicationPreferenceResponse = (unknown);

export type ContactFieldsListContactFieldsData = {
    contactId: string;
    limit?: number;
    skip?: number;
};

export type ContactFieldsListContactFieldsResponse = (ContactFieldsPublic);

export type ContactFieldsCreateContactFieldRouteData = {
    requestBody: ContactFieldCreate;
};

export type ContactFieldsCreateContactFieldRouteResponse = (ContactFieldPublic);

export type ContactFieldsUpdateContactFieldData = {
    fieldId: string;
    requestBody: ContactFieldUpdate;
};

export type ContactFieldsUpdateContactFieldResponse = (ContactFieldPublic);

export type ContactFieldsDeleteContactFieldData = {
    fieldId: string;
};

export type ContactFieldsDeleteContactFieldResponse = (Ok);

export type ContactsBulkUpdateContactsData = {
    requestBody: BulkContactRequest;
};

export type ContactsBulkUpdateContactsResponse = (BulkContactResult);

export type ContactsPreviewBulkContactsData = {
    isArchived?: (boolean | null);
    isFavorite?: (boolean | null);
    limit?: number;
    search?: (string | null);
    selectAllFiltered?: boolean;
    stage?: (string | null);
    tagId?: (string | null);
};

export type ContactsPreviewBulkContactsResponse = (ContactsPublic);

export type ContactsListContactsData = {
    ids?: (Array<(string)> | null);
    includeDeleted?: boolean;
    isArchived?: (boolean | null);
    isFavorite?: (boolean | null);
    limit?: number;
    onlyDeleted?: boolean;
    savedFilterId?: (string | null);
    search?: (string | null);
    skip?: number;
    stage?: (string | null);
    tagId?: (string | null);
};

export type ContactsListContactsResponse = (ContactsPublic);

export type ContactsCreateContactData = {
    requestBody: ContactCreate;
};

export type ContactsCreateContactResponse = (ContactPublic);

export type ContactsListLosingTouchData = {
    limit?: number;
};

export type ContactsListLosingTouchResponse = (ContactsPublic);

export type ContactsListOverdueContactsData = {
    limit?: number;
    offset?: number;
};

export type ContactsListOverdueContactsResponse = (OverdueContactsPublic);

export type ContactsSkipContactData = {
    contactId: string;
};

export type ContactsSkipContactResponse = (ContactPublic);

export type ContactsGetContactData = {
    contactId: string;
};

export type ContactsGetContactResponse = (ContactPublic);

export type ContactsUpdateContactData = {
    contactId: string;
    requestBody: ContactUpdate;
};

export type ContactsUpdateContactResponse = (ContactPublic);

export type ContactsDeleteContactData = {
    contactId: string;
};

export type ContactsDeleteContactResponse = (Ok);

export type ContactsListContactMentionsData = {
    contactId: string;
};

export type ContactsListContactMentionsResponse = (Array<NoteMentionPublic>);

export type ContactsListContactMentionsData = {
    contactId: string;
};

export type ContactsListContactMentionsResponse = (Array<NoteMentionPublic>);

export type ContactsListContactMentionsData = {
    contactId: string;
};

export type ContactsListContactMentionsResponse = (Array<NoteMentionPublic>);

export type ContactsRestoreContactData = {
    contactId: string;
};

export type ContactsRestoreContactResponse = (ContactPublic);

export type ContactsGetDistinctStagesResponse = (Array<(string)>);

export type ContactsGetKanbanBoardData = {
    groupId?: (string | null);
    search?: (string | null);
    tagId?: (string | null);
};

export type ContactsGetKanbanBoardResponse = ({
    [key: string]: ContactsPublic;
});

export type ContactsGetContactStageEventsData = {
    contactId: string;
};

export type ContactsGetContactStageEventsResponse = (ContactStageEventsPublic);

export type CustomFieldsListFieldDefinitionsResponse = (unknown);

export type CustomFieldsCreateFieldDefinitionData = {
    requestBody: CustomFieldDefinitionCreate;
};

export type CustomFieldsCreateFieldDefinitionResponse = (CustomFieldDefinitionPublic);

export type CustomFieldsUpdateFieldDefinitionData = {
    defId: string;
    requestBody: CustomFieldDefinitionUpdate;
};

export type CustomFieldsUpdateFieldDefinitionResponse = (CustomFieldDefinitionPublic);

export type CustomFieldsDeleteFieldDefinitionData = {
    defId: string;
};

export type CustomFieldsDeleteFieldDefinitionResponse = (Ok);

export type CustomFieldsListFieldValuesData = {
    contactId: string;
};

export type CustomFieldsListFieldValuesResponse = (CustomFieldValuesPublic);

export type CustomFieldsCreateFieldValueData = {
    requestBody: CustomFieldValueCreate;
};

export type CustomFieldsCreateFieldValueResponse = (CustomFieldValuePublic);

export type CustomFieldsUpdateFieldValueData = {
    requestBody: CustomFieldValueUpdate;
    valueId: string;
};

export type CustomFieldsUpdateFieldValueResponse = (CustomFieldValuePublic);

export type CustomFieldsDeleteFieldValueData = {
    valueId: string;
};

export type CustomFieldsDeleteFieldValueResponse = (Ok);

export type DebtsListDebtsData = {
    contactId: string;
};

export type DebtsListDebtsResponse = (DebtsPublic);

export type DebtsCreateDebtRouteData = {
    requestBody: DebtCreate;
};

export type DebtsCreateDebtRouteResponse = (DebtPublic);

export type DebtsUpdateDebtData = {
    debtId: string;
    requestBody: DebtUpdate;
};

export type DebtsUpdateDebtResponse = (DebtPublic);

export type DebtsDeleteDebtData = {
    debtId: string;
};

export type DebtsDeleteDebtResponse = (Ok);

export type DebtsRestoreDebtData = {
    debtId: string;
};

export type DebtsRestoreDebtResponse = (unknown);

export type DebtsListDebtPaymentsData = {
    debtId: string;
};

export type DebtsListDebtPaymentsResponse = (Array<DebtPaymentPublic>);

export type DebtsCreateDebtPaymentData = {
    debtId: string;
    requestBody: DebtPaymentCreate;
};

export type DebtsCreateDebtPaymentResponse = (DebtPaymentPublic);

export type DebtsDeleteDebtPaymentData = {
    paymentId: string;
};

export type DebtsDeleteDebtPaymentResponse = (unknown);

export type EmailGmailAuthorizeData = {
    /**
     * Contact ID to associate with this email
     */
    contactId: string;
    /**
     * Email address being authorized
     */
    emailAddress: string;
};

export type EmailGmailAuthorizeResponse = ({
    [key: string]: unknown;
});

export type EmailGmailCallbackData = {
    code: string;
    state: string;
};

export type EmailGmailCallbackResponse = ({
    [key: string]: unknown;
});

export type EmailListEmailTokensData = {
    contactId?: (string | null);
};

export type EmailListEmailTokensResponse = (EmailOAuthTokensPublic);

export type EmailDeleteEmailTokenData = {
    tokenId: string;
};

export type EmailDeleteEmailTokenResponse = ({
    [key: string]: (string);
});

export type EmailPollContactEmailData = {
    contactId: string;
};

export type EmailPollContactEmailResponse = ({
    [key: string]: unknown;
});

export type EmailPollAllEmailsResponse = ({
    [key: string]: unknown;
});

export type GiftsListGiftsData = {
    contactId: string;
};

export type GiftsListGiftsResponse = (GiftsPublic);

export type GiftsCreateGiftRouteData = {
    requestBody: GiftCreate;
};

export type GiftsCreateGiftRouteResponse = (GiftPublic);

export type GiftsUpdateGiftData = {
    giftId: string;
    requestBody: GiftUpdate;
};

export type GiftsUpdateGiftResponse = (GiftPublic);

export type GiftsDeleteGiftData = {
    giftId: string;
};

export type GiftsDeleteGiftResponse = (Ok);

export type GiftsRestoreGiftData = {
    giftId: string;
};

export type GiftsRestoreGiftResponse = (unknown);

export type GiftsGetKanbanBoardResponse = ({
    [key: string]: GiftKanbanColumn;
});

export type GiftsChangeGiftStatusData = {
    giftId: string;
    newStatus: GiftStatus;
};

export type GiftsChangeGiftStatusResponse = (GiftPublic);

export type GraphGetContactsGraphData = {
    /**
     * Hops from seed contacts (1-3)
     */
    depth?: number;
    /**
     * Optional root contact to focus on
     */
    rootContactId?: (string | null);
};

export type GraphGetContactsGraphResponse = (unknown);

export type GraphGetContactGraphData = {
    contactId: string;
    /**
     * Hops from the contact (1-3)
     */
    depth?: number;
};

export type GraphGetContactGraphResponse = (unknown);

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type IcalUploadIcalData = {
    formData: Body_ical_upload_ical;
};

export type IcalUploadIcalResponse = (unknown);

export type IcalConfirmIcalImportData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
};

export type IcalConfirmIcalImportResponse = (unknown);

export type ImportExportImportVcardData = {
    formData: Body_import_export_import_vcard;
};

export type ImportExportImportVcardResponse = (VCardImportResponse);

export type ImportExportExportVcardResponse = (unknown);

export type ImportExportExportJsonResponse = (JsonExportResponse);

export type ImportExportPreviewCsvImportData = {
    formData: Body_import_export_preview_csv_import;
};

export type ImportExportPreviewCsvImportResponse = (CSVPreviewResponse);

export type ImportExportImportCsvData = {
    createMissingTags?: boolean;
    formData: Body_import_export_import_csv;
    mergeDuplicates?: boolean;
    skipDuplicates?: boolean;
};

export type ImportExportImportCsvResponse = (CSVImportResponse);

export type ImportExportExportCsvData = {
    includeFields?: boolean;
    includeTags?: boolean;
};

export type ImportExportExportCsvResponse = (unknown);

export type ImportExportExportCsvData = {
    groupId?: (string | null);
    isArchived?: (boolean | null);
    isFavorite?: (boolean | null);
    limit?: number;
    search?: (string | null);
    selectAllFiltered?: boolean;
    stage?: (string | null);
    tagId?: (string | null);
};

export type ImportExportExportCsvResponse = (unknown);

export type InteractionsListInteractionsData = {
    contactId?: (string | null);
    isDraft?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type InteractionsListInteractionsResponse = (InteractionsPublic);

export type InteractionsCreateInteractionRouteData = {
    requestBody: InteractionCreate;
};

export type InteractionsCreateInteractionRouteResponse = (InteractionPublic);

export type InteractionsUpdateInteractionData = {
    interactionId: string;
    requestBody: InteractionUpdate;
};

export type InteractionsUpdateInteractionResponse = (InteractionPublic);

export type InteractionsDeleteInteractionData = {
    interactionId: string;
};

export type InteractionsDeleteInteractionResponse = (Ok);

export type InteractionsConfirmDraftData = {
    interactionId: string;
};

export type InteractionsConfirmDraftResponse = (InteractionPublic);

export type JournalListJournalEntriesData = {
    limit?: number;
    skip?: number;
};

export type JournalListJournalEntriesResponse = (JournalEntriesPublic);

export type JournalCreateJournalEntryRouteData = {
    requestBody: JournalEntryCreate;
};

export type JournalCreateJournalEntryRouteResponse = (JournalEntryPublic);

export type JournalUpdateJournalEntryData = {
    entryId: string;
    requestBody: JournalEntryUpdate;
};

export type JournalUpdateJournalEntryResponse = (JournalEntryPublic);

export type JournalDeleteJournalEntryData = {
    entryId: string;
};

export type JournalDeleteJournalEntryResponse = (Ok);

export type LifeEventsListLifeEventsData = {
    contactId: string;
};

export type LifeEventsListLifeEventsResponse = (LifeEventsPublic);

export type LifeEventsCreateLifeEventRouteData = {
    requestBody: LifeEventCreate;
};

export type LifeEventsCreateLifeEventRouteResponse = (LifeEventPublic);

export type LifeEventsUpdateLifeEventData = {
    eventId: string;
    requestBody: LifeEventUpdate;
};

export type LifeEventsUpdateLifeEventResponse = (LifeEventPublic);

export type LifeEventsDeleteLifeEventData = {
    eventId: string;
};

export type LifeEventsDeleteLifeEventResponse = (Ok);

export type LifeEventsRestoreLifeEventData = {
    eventId: string;
};

export type LifeEventsRestoreLifeEventResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaRecommendationsListMediaRecommendationsData = {
    contactId: string;
};

export type MediaRecommendationsListMediaRecommendationsResponse = (MediaRecommendationsPublic);

export type MediaRecommendationsCreateMediaRecommendationRouteData = {
    requestBody: MediaRecommendationCreate;
};

export type MediaRecommendationsCreateMediaRecommendationRouteResponse = (MediaRecommendationPublic);

export type MediaRecommendationsUpdateMediaRecommendationData = {
    recId: string;
    requestBody: MediaRecommendationUpdate;
};

export type MediaRecommendationsUpdateMediaRecommendationResponse = (MediaRecommendationPublic);

export type MediaRecommendationsDeleteMediaRecommendationData = {
    recId: string;
};

export type MediaRecommendationsDeleteMediaRecommendationResponse = (Ok);

export type NotesListNotesData = {
    contactId: string;
    limit?: number;
    skip?: number;
};

export type NotesListNotesResponse = (NotesPublic);

export type NotesCreateNoteRouteData = {
    requestBody: NoteCreate;
};

export type NotesCreateNoteRouteResponse = (NotePublic);

export type NotesUpdateNoteRouteData = {
    noteId: string;
    requestBody: NoteUpdate;
};

export type NotesUpdateNoteRouteResponse = (NotePublic);

export type NotesDeleteNoteData = {
    noteId: string;
};

export type NotesDeleteNoteResponse = (Ok);

export type NotesRestoreNoteData = {
    noteId: string;
};

export type NotesRestoreNoteResponse = (unknown);

export type OrganizationsListOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsListOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsGetOrganizationData = {
    organizationId: string;
};

export type OrganizationsGetOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    organizationId: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    organizationId: string;
};

export type OrganizationsDeleteOrganizationResponse = (unknown);

export type OrganizationsGetOrganizationWithContactsData = {
    organizationId: string;
};

export type OrganizationsGetOrganizationWithContactsResponse = ({
    [key: string]: unknown;
});

export type PetsListPetsData = {
    contactId: string;
};

export type PetsListPetsResponse = (PetsPublic);

export type PetsCreatePetRouteData = {
    requestBody: PetCreate;
};

export type PetsCreatePetRouteResponse = (PetPublic);

export type PetsUpdatePetData = {
    petId: string;
    requestBody: PetUpdate;
};

export type PetsUpdatePetResponse = (PetPublic);

export type PetsDeletePetData = {
    petId: string;
};

export type PetsDeletePetResponse = (Ok);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PrivateSeedDataData = {
    /**
     * Number of contacts to seed
     */
    count?: number;
    /**
     * Wipe existing data before seeding
     */
    reset?: boolean;
    /**
     * RNG seed for determinism
     */
    rngSeed?: (number | null);
};

export type PrivateSeedDataResponse = ({
    [key: string]: unknown;
});

export type RelationshipInverseMapListInverseMapsData = {
    limit?: number;
    skip?: number;
};

export type RelationshipInverseMapListInverseMapsResponse = (InverseRelationshipMapsPublic);

export type RelationshipInverseMapCreateInverseMapData = {
    requestBody: InverseRelationshipMapCreate;
};

export type RelationshipInverseMapCreateInverseMapResponse = (InverseRelationshipMapPublic);

export type RelationshipInverseMapGetInverseMapData = {
    mapId: string;
};

export type RelationshipInverseMapGetInverseMapResponse = (InverseRelationshipMapPublic);

export type RelationshipInverseMapUpdateInverseMapData = {
    mapId: string;
    requestBody: InverseRelationshipMapUpdate;
};

export type RelationshipInverseMapUpdateInverseMapResponse = (InverseRelationshipMapPublic);

export type RelationshipInverseMapDeleteInverseMapData = {
    mapId: string;
};

export type RelationshipInverseMapDeleteInverseMapResponse = (unknown);

export type RelationshipInverseMapSeedInverseMapEndpointResponse = (unknown);

export type RelationshipInverseMapLookupInverseData = {
    relationshipType: string;
};

export type RelationshipInverseMapLookupInverseResponse = (unknown);

export type RelationshipsLookupInverseData = {
    type: string;
};

export type RelationshipsLookupInverseResponse = ({
    [key: string]: (string | null);
});

export type RelationshipsListRelationshipsData = {
    contactId: string;
};

export type RelationshipsListRelationshipsResponse = (RelationshipsPublic);

export type RelationshipsCreateRelationshipRouteData = {
    requestBody: RelationshipCreate;
};

export type RelationshipsCreateRelationshipRouteResponse = (RelationshipPublic);

export type RelationshipsUpdateRelationshipData = {
    relId: string;
    requestBody: RelationshipUpdate;
};

export type RelationshipsUpdateRelationshipResponse = (RelationshipPublic);

export type RelationshipsDeleteRelationshipData = {
    relId: string;
};

export type RelationshipsDeleteRelationshipResponse = (Ok);

export type RemindersListRemindersData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RemindersListRemindersResponse = (RemindersPublic);

export type RemindersCreateReminderRouteData = {
    requestBody: ReminderCreate;
};

export type RemindersCreateReminderRouteResponse = (ReminderPublic);

export type RemindersListDueRemindersData = {
    limit?: number;
};

export type RemindersListDueRemindersResponse = (RemindersDuePublic);

export type RemindersUpdateReminderData = {
    reminderId: string;
    requestBody: ReminderUpdate;
};

export type RemindersUpdateReminderResponse = (ReminderPublic);

export type RemindersDeleteReminderData = {
    reminderId: string;
};

export type RemindersDeleteReminderResponse = (Ok);

export type RemindersSnoozeReminderData = {
    minutes?: (number | null);
    reason?: (string | null);
    reminderId: string;
    requestBody?: (ReminderSnoozeRequest | null);
};

export type RemindersSnoozeReminderResponse = (ReminderPublic);

export type RemindersDismissReminderData = {
    reminderId: string;
};

export type RemindersDismissReminderResponse = (ReminderPublic);

export type RemindersGetSnoozeHistoryData = {
    reminderId: string;
};

export type RemindersGetSnoozeHistoryResponse = (Array<ReminderSnoozeHistoryEntry>);

export type RemindersGetSnoozeStatsData = {
    days?: number;
};

export type RemindersGetSnoozeStatsResponse = (Array<ReminderSnoozeStat>);

export type RemindersGetChronicSnoozersData = {
    days?: number;
    threshold?: number;
};

export type RemindersGetChronicSnoozersResponse = (Array<ChronicSnoozer>);

export type RemindersRestoreReminderData = {
    reminderId: string;
};

export type RemindersRestoreReminderResponse = (unknown);

export type SavedFiltersListSavedFiltersData = {
    limit?: number;
    skip?: number;
};

export type SavedFiltersListSavedFiltersResponse = (SavedFiltersPublic);

export type SavedFiltersCreateSavedFilterRouteData = {
    requestBody: SavedFilterCreate;
};

export type SavedFiltersCreateSavedFilterRouteResponse = (SavedFilterPublic);

export type SavedFiltersUpdateSavedFilterRouteData = {
    filterId: string;
    requestBody: SavedFilterUpdate;
};

export type SavedFiltersUpdateSavedFilterRouteResponse = (SavedFilterPublic);

export type SavedFiltersDeleteSavedFilterRouteData = {
    filterId: string;
};

export type SavedFiltersDeleteSavedFilterRouteResponse = (unknown);

export type SearchSearchData = {
    /**
     * Max results per type
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type SearchSearchResponse = (SearchResponse);

export type SetupSetupPageData = {
    token: string;
};

export type SetupSetupPageResponse = (string);

export type SetupSetupSubmitData = {
    requestBody: SetupSubmit;
};

export type SetupSetupSubmitResponse = (UserPublic);

export type TagsListTagsData = {
    limit?: number;
    skip?: number;
};

export type TagsListTagsResponse = (TagsPublic);

export type TagsCreateTagRouteData = {
    requestBody: TagCreate;
};

export type TagsCreateTagRouteResponse = (TagPublic);

export type TagsUpdateTagData = {
    requestBody: TagUpdate;
    tagId: string;
};

export type TagsUpdateTagResponse = (TagPublic);

export type TagsDeleteTagData = {
    tagId: string;
};

export type TagsDeleteTagResponse = (Ok);

export type TagSharesPreviewTagShareData = {
    tagId: string;
};

export type TagSharesPreviewTagShareResponse = (TagSharePreview);

export type TagSharesPreviewTagShareData = {
    tagId: string;
};

export type TagSharesPreviewTagShareResponse = (TagSharePreview);

export type TagSharesCreateTagShareData = {
    requestBody: _ShareIn;
};

export type TagSharesCreateTagShareResponse = (TagSharePublic);

export type TagSharesListTagSharesData = {
    tagId: string;
};

export type TagSharesListTagSharesResponse = (TagSharesPublic);

export type TagSharesDeleteTagShareData = {
    granteeId: string;
    tagId: string;
};

export type TagSharesDeleteTagShareResponse = ({
    [key: string]: (string);
});

export type TagSharesLogTagShareAuditData = {
    granteeId: string;
    tagId: string;
};

export type TagSharesLogTagShareAuditResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsEnvironmentResponse = (EnvironmentInfo);

export type VCardConflictsListVcardConflictsData = {
    limit?: number;
    skip?: number;
};

export type VCardConflictsListVcardConflictsResponse = (VCardConflictsPublic);

export type VCardConflictsResolveVcardConflictData = {
    conflictId: string;
    resolutionType: string;
};

export type VCardConflictsResolveVcardConflictResponse = (VCardConflictPublic);

export type VCardConflictsDeleteVcardConflictData = {
    conflictId: string;
};

export type VCardConflictsDeleteVcardConflictResponse = (void);

export type WebhooksTwilioWebhookData = {
    apiKey: string;
};

export type WebhooksTwilioWebhookResponse = (WebhookEventResponse);

export type WebhooksListWebhooksResponse = (WebhookEndpointsPublic);

export type WebhooksCreateWebhookData = {
    requestBody: WebhookEndpointBase;
};

export type WebhooksCreateWebhookResponse = (WebhookEndpointCreated);

export type WebhooksUpdateWebhookData = {
    requestBody: WebhookEndpointBase;
    webhookId: string;
};

export type WebhooksUpdateWebhookResponse = (WebhookEndpointPublic);

export type WebhooksDeleteWebhookData = {
    webhookId: string;
};

export type WebhooksDeleteWebhookResponse = (Ok);

export type WebhooksInboundWebhookData = {
    apiKey: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type WebhooksInboundWebhookResponse = (WebhookEventResponse);