// This file is auto-generated by @hey-api/openapi-ts

export type _MentionSourceContact = {
    id: string;
    first_name: string;
    last_name?: (string | null);
    avatar_url?: (string | null);
};

export type _ShareIn = {
    tag_id: string;
    grantee_id: string;
};

export type ActivityLogPublic = {
    id: string;
    owner_id: string;
    actor_id: (string | null);
    entity_type: string;
    entity_id: string;
    action: string;
    changes_json: ({
    [key: string]: unknown;
} | null);
    occurred_at: string;
};

export type ActivityLogsPublic = {
    data: Array<ActivityLogPublic>;
    count: number;
};

export type AddressCreate = {
    /**
     * Label like "home", "work", "other".
     */
    label?: string;
    /**
     * Street line 1.
     */
    street?: (string | null);
    /**
     * Apartment, suite, floor, etc.
     */
    extended?: (string | null);
    /**
     * City.
     */
    city?: (string | null);
    /**
     * State, province, or region.
     */
    region?: (string | null);
    /**
     * ZIP or postal code.
     */
    postal_code?: (string | null);
    /**
     * Country.
     */
    country?: (string | null);
    /**
     * Geocoded latitude; used for map visualization.
     */
    latitude?: (number | null);
    /**
     * Geocoded longitude; used for map visualization.
     */
    longitude?: (number | null);
    contact_id: string;
};

export type AddressPublic = {
    /**
     * Label like "home", "work", "other".
     */
    label?: string;
    /**
     * Street line 1.
     */
    street?: (string | null);
    /**
     * Apartment, suite, floor, etc.
     */
    extended?: (string | null);
    /**
     * City.
     */
    city?: (string | null);
    /**
     * State, province, or region.
     */
    region?: (string | null);
    /**
     * ZIP or postal code.
     */
    postal_code?: (string | null);
    /**
     * Country.
     */
    country?: (string | null);
    /**
     * Geocoded latitude; used for map visualization.
     */
    latitude?: (number | null);
    /**
     * Geocoded longitude; used for map visualization.
     */
    longitude?: (number | null);
    id: string;
    contact_id: string;
};

export type AddressUpdate = {
    label?: (string | null);
    street?: (string | null);
    extended?: (string | null);
    city?: (string | null);
    region?: (string | null);
    postal_code?: (string | null);
    country?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type Body_import_vcard_import_export_import_vcard_post = {
    file: (Blob | File);
};

export type Body_login_access_token_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Filter criteria matching list_contacts parameters.
 */
export type BulkContactFilter = {
    search?: (string | null);
    tag_id?: (string | null);
    group_id?: (string | null);
    is_favorite?: (boolean | null);
    is_archived?: (boolean | null);
    stage?: (string | null);
};

/**
 * A single operation to apply to matching contacts.
 */
export type BulkContactOperation = {
    add_tag_ids?: (Array<(string)> | null);
    remove_tag_ids?: (Array<(string)> | null);
    add_group_ids?: (Array<(string)> | null);
    remove_group_ids?: (Array<(string)> | null);
    set_is_archived?: (boolean | null);
    set_is_favorite?: (boolean | null);
};

/**
 * Bulk operation request body.
 */
export type BulkContactRequest = {
    contact_ids?: (Array<(string)> | null);
    select_all_filtered?: boolean;
    filters?: (BulkContactFilter | null);
    limit?: number;
    operations: BulkContactOperation;
};

/**
 * Bulk operation result.
 */
export type BulkContactResult = {
    updated_count: number;
    skipped_count: number;
    failed_ids?: Array<(string)>;
};

export type CalendarEntry = {
    contact_id: string;
    name: string;
    type: string;
    age: (number | null);
};

export type CalendarMonthResponse = {
    month: string;
    days: {
        [key: string]: Array<CalendarEntry>;
    };
};

export type ContactCreate = {
    /**
     * Given name; required.
     */
    first_name: string;
    /**
     * Family name.
     */
    last_name?: (string | null);
    /**
     * Middle name or initial.
     */
    middle_name?: (string | null);
    /**
     * Honorific like Dr., Mr., Ms.
     */
    prefix?: (string | null);
    /**
     * Suffix like Jr., PhD.
     */
    suffix?: (string | null);
    /**
     * Preferred or informal name.
     */
    nickname?: (string | null);
    /**
     * Organization name.
     */
    company?: (string | null);
    /**
     * Department within the company.
     */
    department?: (string | null);
    /**
     * Job title.
     */
    title?: (string | null);
    /**
     * Date of birth; used for milestone and birthday reminders.
     */
    birthday?: (string | null);
    /**
     * Short story of how the introduction happened.
     */
    how_we_met?: (string | null);
    /**
     * Pinned to the top of contact lists.
     */
    is_favorite?: boolean;
    /**
     * Soft-deleted; excluded from default lists.
     */
    is_archived?: boolean;
    /**
     * Marks the contact as deceased.
     */
    is_deceased?: boolean;
    /**
     * Date the contact passed away.
     */
    deceased_at?: (string | null);
    /**
     * Target days between interactions; drives losing-touch cadence.
     */
    contact_frequency_days?: (number | null);
    /**
     * Kanban stage like Active, Dormant, Lost.
     */
    stage?: (string | null);
    tag_ids?: (Array<(string)> | null);
    group_ids?: (Array<(string)> | null);
};

export type ContactFieldCreate = {
    /**
     * Kind of contact info (email or phone).
     */
    field_type: ContactFieldType;
    /**
     * Label like "home", "work", "cell", "twitter".
     */
    label: string;
    /**
     * The actual email address, phone number, etc.
     */
    value: string;
    /**
     * Marks the primary entry for this field_type on the contact.
     */
    is_primary?: boolean;
    /**
     * Display order within the same field_type.
     */
    sort_order?: number;
    contact_id: string;
};

export type ContactFieldPublic = {
    /**
     * Kind of contact info (email or phone).
     */
    field_type: ContactFieldType;
    /**
     * Label like "home", "work", "cell", "twitter".
     */
    label: string;
    /**
     * The actual email address, phone number, etc.
     */
    value: string;
    /**
     * Marks the primary entry for this field_type on the contact.
     */
    is_primary?: boolean;
    /**
     * Display order within the same field_type.
     */
    sort_order?: number;
    id: string;
    contact_id: string;
};

export type ContactFieldType = 'email' | 'phone';

export type ContactFieldUpdate = {
    field_type?: (ContactFieldType | null);
    label?: (string | null);
    value?: (string | null);
    is_primary?: (boolean | null);
    sort_order?: (number | null);
};

export type ContactPublic = {
    /**
     * Given name; required.
     */
    first_name: string;
    /**
     * Family name.
     */
    last_name?: (string | null);
    /**
     * Middle name or initial.
     */
    middle_name?: (string | null);
    /**
     * Honorific like Dr., Mr., Ms.
     */
    prefix?: (string | null);
    /**
     * Suffix like Jr., PhD.
     */
    suffix?: (string | null);
    /**
     * Preferred or informal name.
     */
    nickname?: (string | null);
    /**
     * Organization name.
     */
    company?: (string | null);
    /**
     * Department within the company.
     */
    department?: (string | null);
    /**
     * Job title.
     */
    title?: (string | null);
    /**
     * Date of birth; used for milestone and birthday reminders.
     */
    birthday?: (string | null);
    /**
     * Short story of how the introduction happened.
     */
    how_we_met?: (string | null);
    /**
     * Pinned to the top of contact lists.
     */
    is_favorite?: boolean;
    /**
     * Soft-deleted; excluded from default lists.
     */
    is_archived?: boolean;
    /**
     * Marks the contact as deceased.
     */
    is_deceased?: boolean;
    /**
     * Date the contact passed away.
     */
    deceased_at?: (string | null);
    /**
     * Target days between interactions; drives losing-touch cadence.
     */
    contact_frequency_days?: (number | null);
    /**
     * Kanban stage like Active, Dormant, Lost.
     */
    stage?: (string | null);
    id: string;
    avatar_url: (string | null);
    last_contacted_at: (string | null);
    created_at: string;
    updated_at: string;
    deleted_at?: (string | null);
    tags?: Array<TagPublic>;
    groups?: Array<GroupPublic>;
};

export type ContactsPublic = {
    data: Array<ContactPublic>;
    count: number;
};

export type ContactUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    middle_name?: (string | null);
    prefix?: (string | null);
    suffix?: (string | null);
    nickname?: (string | null);
    company?: (string | null);
    department?: (string | null);
    title?: (string | null);
    birthday?: (string | null);
    how_we_met?: (string | null);
    is_favorite?: (boolean | null);
    is_archived?: (boolean | null);
    is_deceased?: (boolean | null);
    deceased_at?: (string | null);
    contact_frequency_days?: (number | null);
    stage?: (string | null);
    tag_ids?: (Array<(string)> | null);
    group_ids?: (Array<(string)> | null);
};

export type CustomFieldDefinitionCreate = {
    /**
     * Custom field name shown in the UI.
     */
    name: string;
    /**
     * Field type: text, number, date, boolean, or select.
     */
    field_type?: string;
    /**
     * Help text displayed alongside the field in the UI.
     */
    description?: (string | null);
    /**
     * Comma-separated options for field_type="select".
     */
    options?: (string | null);
    /**
     * Icon slug for the UI (e.g. "heart", "book").
     */
    icon?: (string | null);
};

export type CustomFieldDefinitionPublic = {
    /**
     * Custom field name shown in the UI.
     */
    name: string;
    /**
     * Field type: text, number, date, boolean, or select.
     */
    field_type?: string;
    /**
     * Help text displayed alongside the field in the UI.
     */
    description?: (string | null);
    /**
     * Comma-separated options for field_type="select".
     */
    options?: (string | null);
    /**
     * Icon slug for the UI (e.g. "heart", "book").
     */
    icon?: (string | null);
    id: string;
    created_at: string;
};

export type CustomFieldDefinitionUpdate = {
    name?: (string | null);
    field_type?: (string | null);
    description?: (string | null);
    options?: (string | null);
    icon?: (string | null);
};

export type CustomFieldValueCreate = {
    /**
     * Value as a string; coerced from the declared field_type.
     */
    value: string;
    contact_id: string;
    field_definition_id: string;
};

export type CustomFieldValuePublic = {
    /**
     * Value as a string; coerced from the declared field_type.
     */
    value: string;
    id: string;
    contact_id: string;
    field_definition_id: string;
    field_name?: (string | null);
};

export type CustomFieldValueUpdate = {
    value?: (string | null);
};

export type DebtCreate = {
    /**
     * Who owes whom: i_owe (you owe them) or they_owe (they owe you).
     */
    direction: DebtDirection;
    /**
     * Amount owed; must be greater than zero.
     */
    amount: number;
    /**
     * ISO 4217 currency code.
     */
    currency?: string;
    /**
     * What the debt is for.
     */
    reason?: (string | null);
    /**
     * Marked paid off.
     */
    is_settled?: boolean;
    /**
     * Date the debt was settled.
     */
    settled_at?: (string | null);
    contact_id: string;
};

export type DebtDirection = 'i_owe' | 'they_owe';

export type DebtPublic = {
    /**
     * Who owes whom: i_owe (you owe them) or they_owe (they owe you).
     */
    direction: DebtDirection;
    /**
     * Amount owed; must be greater than zero.
     */
    amount: number;
    /**
     * ISO 4217 currency code.
     */
    currency?: string;
    /**
     * What the debt is for.
     */
    reason?: (string | null);
    /**
     * Marked paid off.
     */
    is_settled?: boolean;
    /**
     * Date the debt was settled.
     */
    settled_at?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
};

export type DebtsPublic = {
    data: Array<DebtPublic>;
    count: number;
};

export type DebtUpdate = {
    direction?: (DebtDirection | null);
    amount?: (number | null);
    currency?: (string | null);
    reason?: (string | null);
    is_settled?: (boolean | null);
    settled_at?: (string | null);
};

export type GiftCreate = {
    /**
     * Gift name.
     */
    name: string;
    /**
     * Details about the gift.
     */
    description?: (string | null);
    /**
     * Lifecycle: idea, given, or received.
     */
    status?: GiftStatus;
    /**
     * Occasion like Birthday, Christmas, Housewarming.
     */
    occasion?: (string | null);
    /**
     * When the gift was given or received.
     */
    gift_date?: (string | null);
    /**
     * Monetary cost or value.
     */
    value_amount?: (number | null);
    /**
     * ISO 4217 currency code.
     */
    value_currency?: string;
    /**
     * Link to the product page (e.g. Amazon).
     */
    url?: (string | null);
    contact_id: string;
};

export type GiftPublic = {
    /**
     * Gift name.
     */
    name: string;
    /**
     * Details about the gift.
     */
    description?: (string | null);
    /**
     * Lifecycle: idea, given, or received.
     */
    status?: GiftStatus;
    /**
     * Occasion like Birthday, Christmas, Housewarming.
     */
    occasion?: (string | null);
    /**
     * When the gift was given or received.
     */
    gift_date?: (string | null);
    /**
     * Monetary cost or value.
     */
    value_amount?: (number | null);
    /**
     * ISO 4217 currency code.
     */
    value_currency?: string;
    /**
     * Link to the product page (e.g. Amazon).
     */
    url?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
};

export type GiftsPublic = {
    data: Array<GiftPublic>;
    count: number;
};

export type GiftStatus = 'idea' | 'given' | 'received';

export type GiftUpdate = {
    name?: (string | null);
    description?: (string | null);
    status?: (GiftStatus | null);
    occasion?: (string | null);
    gift_date?: (string | null);
    value_amount?: (number | null);
    value_currency?: (string | null);
    url?: (string | null);
};

export type GroupCreate = {
    /**
     * Group name, 1-255 chars.
     */
    name: string;
    /**
     * Optional group description.
     */
    description?: (string | null);
};

export type GroupPublic = {
    /**
     * Group name, 1-255 chars.
     */
    name: string;
    /**
     * Optional group description.
     */
    description?: (string | null);
    id: string;
    created_at: string;
};

export type GroupsPublic = {
    data: Array<GroupPublic>;
    count: number;
};

export type GroupUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InteractionAttendeeSummary = {
    id: string;
    first_name: string;
    last_name?: (string | null);
    avatar_url?: (string | null);
};

export type InteractionChannel = 'call' | 'in_person' | 'text' | 'email' | 'video' | 'social' | 'other';

export type InteractionCreate = {
    /**
     * How the interaction happened (call, in_person, text, etc.).
     */
    channel: InteractionChannel;
    /**
     * When the interaction actually took place.
     */
    occurred_at: string;
    /**
     * Conversation summary, action items, etc.
     */
    notes?: (string | null);
    /**
     * Emoji or keyword capturing the tone.
     */
    mood?: (string | null);
    /**
     * Length of the interaction in minutes.
     */
    duration_minutes?: (number | null);
    /**
     * Contacts that attended; must have at least one.
     */
    attendee_ids: Array<(string)>;
};

export type InteractionPublic = {
    /**
     * How the interaction happened (call, in_person, text, etc.).
     */
    channel: InteractionChannel;
    /**
     * When the interaction actually took place.
     */
    occurred_at: string;
    /**
     * Conversation summary, action items, etc.
     */
    notes?: (string | null);
    /**
     * Emoji or keyword capturing the tone.
     */
    mood?: (string | null);
    /**
     * Length of the interaction in minutes.
     */
    duration_minutes?: (number | null);
    id: string;
    attendees?: Array<InteractionAttendeeSummary>;
    created_at: string;
};

export type InteractionsPublic = {
    data: Array<InteractionPublic>;
    count: number;
};

export type InteractionUpdate = {
    channel?: (InteractionChannel | null);
    occurred_at?: (string | null);
    notes?: (string | null);
    mood?: (string | null);
    duration_minutes?: (number | null);
    /**
     * Replace the attendee set; must have at least one if provided.
     */
    attendee_ids?: (Array<(string)> | null);
};

export type JournalEntriesPublic = {
    data: Array<JournalEntryPublic>;
    count: number;
};

export type JournalEntryCreate = {
    /**
     * Entry body, 1-50000 chars.
     */
    body: string;
    /**
     * Emoji or keyword capturing the mood.
     */
    mood?: (string | null);
    /**
     * Date the entry is about (may differ from created_at).
     */
    entry_date: string;
};

export type JournalEntryPublic = {
    /**
     * Entry body, 1-50000 chars.
     */
    body: string;
    /**
     * Emoji or keyword capturing the mood.
     */
    mood?: (string | null);
    /**
     * Date the entry is about (may differ from created_at).
     */
    entry_date: string;
    id: string;
    created_at: string;
    updated_at: string;
};

export type JournalEntryUpdate = {
    body?: (string | null);
    mood?: (string | null);
    entry_date?: (string | null);
};

export type LifeEventCreate = {
    /**
     * Kind of milestone: job_change, move, wedding, baby, graduation, birthday, anniversary, etc.
     */
    event_type: string;
    /**
     * Event title.
     */
    title: string;
    /**
     * Extra details about the event.
     */
    description?: (string | null);
    /**
     * Date the event happened.
     */
    occurred_at: string;
    /**
     * If true, auto-create a yearly recurring reminder on this date.
     */
    create_annual_reminder?: boolean;
    contact_id: string;
};

export type LifeEventPublic = {
    /**
     * Kind of milestone: job_change, move, wedding, baby, graduation, birthday, anniversary, etc.
     */
    event_type: string;
    /**
     * Event title.
     */
    title: string;
    /**
     * Extra details about the event.
     */
    description?: (string | null);
    /**
     * Date the event happened.
     */
    occurred_at: string;
    /**
     * If true, auto-create a yearly recurring reminder on this date.
     */
    create_annual_reminder?: boolean;
    id: string;
    contact_id: string;
    created_at: string;
};

export type LifeEventsPublic = {
    data: Array<LifeEventPublic>;
    count: number;
};

export type LifeEventUpdate = {
    event_type?: (string | null);
    title?: (string | null);
    description?: (string | null);
    occurred_at?: (string | null);
    create_annual_reminder?: (boolean | null);
};

export type MediaCategory = 'movie' | 'tv_show' | 'podcast' | 'musician' | 'book' | 'other';

export type MediaRecommendationCreate = {
    /**
     * Media category: movie, tv_show, podcast, musician, book, or other.
     */
    category: MediaCategory;
    /**
     * Title of the work.
     */
    title: string;
    /**
     * Author, director, artist, or similar creator.
     */
    creator?: (string | null);
    /**
     * Why it was recommended or personal reaction.
     */
    note?: (string | null);
    /**
     * Date the recommendation was made.
     */
    recommended_at?: (string | null);
    contact_id: string;
};

export type MediaRecommendationPublic = {
    /**
     * Media category: movie, tv_show, podcast, musician, book, or other.
     */
    category: MediaCategory;
    /**
     * Title of the work.
     */
    title: string;
    /**
     * Author, director, artist, or similar creator.
     */
    creator?: (string | null);
    /**
     * Why it was recommended or personal reaction.
     */
    note?: (string | null);
    /**
     * Date the recommendation was made.
     */
    recommended_at?: (string | null);
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type MediaRecommendationsPublic = {
    data: Array<MediaRecommendationPublic>;
    count: number;
};

export type MediaRecommendationUpdate = {
    category?: (MediaCategory | null);
    title?: (string | null);
    creator?: (string | null);
    note?: (string | null);
    recommended_at?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteCreate = {
    /**
     * Note body, 1-50000 chars.
     */
    body: string;
    contact_id: string;
};

export type NoteMentionPublic = {
    note_id: string;
    note_body: string;
    note_created_at: string;
    source_contact: _MentionSourceContact;
};

export type NotePublic = {
    /**
     * Note body, 1-50000 chars.
     */
    body: string;
    id: string;
    contact_id: string;
    created_at: string;
    updated_at: string;
};

export type NotesPublic = {
    data: Array<NotePublic>;
    count: number;
};

export type NoteUpdate = {
    body?: (string | null);
};

export type PetCreate = {
    /**
     * Pet's name.
     */
    name: string;
    /**
     * Species like dog, cat, bird.
     */
    species?: (string | null);
    /**
     * Breed, if known.
     */
    breed?: (string | null);
    /**
     * Freeform notes (e.g. allergies, birthday).
     */
    notes?: (string | null);
    contact_id: string;
};

export type PetPublic = {
    /**
     * Pet's name.
     */
    name: string;
    /**
     * Species like dog, cat, bird.
     */
    species?: (string | null);
    /**
     * Breed, if known.
     */
    breed?: (string | null);
    /**
     * Freeform notes (e.g. allergies, birthday).
     */
    notes?: (string | null);
    id: string;
    contact_id: string;
};

export type PetUpdate = {
    name?: (string | null);
    species?: (string | null);
    breed?: (string | null);
    notes?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RelationshipCreate = {
    /**
     * Kind of relationship: spouse, child, parent, sibling, friend, colleague, etc.
     */
    relationship_type: string;
    /**
     * Additional context about the relationship.
     */
    notes?: (string | null);
    contact_id: string;
    related_contact_id: string;
    /**
     * Type for the auto-generated inverse row. If omitted, the server infers it from a known map of symmetric/asymmetric types and returns 422 when it cannot.
     */
    inverse_relationship_type?: (string | null);
};

export type RelationshipPublic = {
    /**
     * Kind of relationship: spouse, child, parent, sibling, friend, colleague, etc.
     */
    relationship_type: string;
    /**
     * Additional context about the relationship.
     */
    notes?: (string | null);
    id: string;
    contact_id: string;
    related_contact_id: string;
    inverse_id?: (string | null);
};

export type RelationshipUpdate = {
    relationship_type?: (string | null);
    notes?: (string | null);
};

export type ReminderCreate = {
    /**
     * Reminder title.
     */
    title: string;
    /**
     * Extra details shown with the reminder.
     */
    description?: (string | null);
    /**
     * When to fire the reminder.
     */
    remind_at: string;
    /**
     * How often the reminder repeats.
     */
    frequency?: ReminderFrequency;
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    contact_id?: (string | null);
};

export type ReminderFrequency = 'once' | 'daily' | 'weekly' | 'monthly' | 'yearly';

export type ReminderPublic = {
    /**
     * Reminder title.
     */
    title: string;
    /**
     * Extra details shown with the reminder.
     */
    description?: (string | null);
    /**
     * When to fire the reminder.
     */
    remind_at: string;
    /**
     * How often the reminder repeats.
     */
    frequency?: ReminderFrequency;
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    id: string;
    contact_id: (string | null);
    last_sent_at: (string | null);
    snoozed_until: (string | null);
    created_at: string;
};

export type RemindersPublic = {
    data: Array<ReminderPublic>;
    count: number;
};

export type ReminderUpdate = {
    title?: (string | null);
    description?: (string | null);
    remind_at?: (string | null);
    frequency?: (ReminderFrequency | null);
    is_active?: (boolean | null);
};

export type TagCreate = {
    /**
     * Tag name, 1-100 chars.
     */
    name: string;
    /**
     * Optional hex color like #ff0000 for UI display.
     */
    color?: (string | null);
};

export type TagPublic = {
    /**
     * Tag name, 1-100 chars.
     */
    name: string;
    /**
     * Optional hex color like #ff0000 for UI display.
     */
    color?: (string | null);
    id: string;
    created_at: string;
};

export type TagSharePublic = {
    tag_id: string;
    grantee_id: string;
    grantee_email: string;
    created_at: string;
};

export type TagSharesPublic = {
    data: Array<TagSharePublic>;
    count: number;
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type TagUpdate = {
    name?: (string | null);
    color?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    /**
     * Login email; must be unique.
     */
    email: string;
    /**
     * Whether the account can log in.
     */
    is_active?: boolean;
    /**
     * Grants admin-only endpoints.
     */
    is_superuser?: boolean;
    /**
     * Display name; optional.
     */
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    /**
     * Login email; must be unique.
     */
    email: string;
    /**
     * Whether the account can log in.
     */
    is_active?: boolean;
    /**
     * Grants admin-only endpoints.
     */
    is_superuser?: boolean;
    /**
     * Display name; optional.
     */
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    /**
     * Whether the account can log in.
     */
    is_active?: boolean;
    /**
     * Grants admin-only endpoints.
     */
    is_superuser?: boolean;
    /**
     * Display name; optional.
     */
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WebhookEndpointBase = {
    /**
     * Human-readable endpoint name.
     */
    name: string;
    /**
     * Target URL for outbound webhooks; null for inbound.
     */
    url?: (string | null);
    /**
     * "inbound" or "outbound".
     */
    direction: string;
    /**
     * Comma-separated event types (e.g. contact.created,interaction.logged).
     */
    event_types?: (string | null);
    /**
     * Enable or disable without deleting.
     */
    is_active?: boolean;
    /**
     * HMAC secret for verifying inbound payloads.
     */
    secret?: (string | null);
};

export type ListActivityLogsActivityLogsGetData = {
    entityId?: (string | null);
    entityType?: (string | null);
    limit?: number;
    offset?: number;
    tagId?: (string | null);
};

export type ListActivityLogsActivityLogsGetResponse = (ActivityLogsPublic);

export type ListAddressesAddressesContactContactIdGetData = {
    contactId: string;
};

export type ListAddressesAddressesContactContactIdGetResponse = (unknown);

export type CreateAddressRouteAddressesPostData = {
    requestBody: AddressCreate;
};

export type CreateAddressRouteAddressesPostResponse = (AddressPublic);

export type UpdateAddressAddressesAddressIdPatchData = {
    addressId: string;
    requestBody: AddressUpdate;
};

export type UpdateAddressAddressesAddressIdPatchResponse = (AddressPublic);

export type DeleteAddressAddressesAddressIdDeleteData = {
    addressId: string;
};

export type DeleteAddressAddressesAddressIdDeleteResponse = (unknown);

export type GetCalendarMonthCalendarMonthYyyyMmGetData = {
    yyyyMm: string;
};

export type GetCalendarMonthCalendarMonthYyyyMmGetResponse = (CalendarMonthResponse);

export type ListContactFieldsContactFieldsContactContactIdGetData = {
    contactId: string;
    limit?: number;
    skip?: number;
};

export type ListContactFieldsContactFieldsContactContactIdGetResponse = (unknown);

export type CreateContactFieldRouteContactFieldsPostData = {
    requestBody: ContactFieldCreate;
};

export type CreateContactFieldRouteContactFieldsPostResponse = (ContactFieldPublic);

export type UpdateContactFieldContactFieldsFieldIdPatchData = {
    fieldId: string;
    requestBody: ContactFieldUpdate;
};

export type UpdateContactFieldContactFieldsFieldIdPatchResponse = (ContactFieldPublic);

export type DeleteContactFieldContactFieldsFieldIdDeleteData = {
    fieldId: string;
};

export type DeleteContactFieldContactFieldsFieldIdDeleteResponse = (unknown);

export type BulkUpdateContactsContactsBulkPatchData = {
    requestBody: BulkContactRequest;
};

export type BulkUpdateContactsContactsBulkPatchResponse = (BulkContactResult);

export type PreviewBulkContactsContactsBulkPreviewGetData = {
    groupId?: (string | null);
    isArchived?: (boolean | null);
    isFavorite?: (boolean | null);
    limit?: number;
    search?: (string | null);
    selectAllFiltered?: boolean;
    stage?: (string | null);
    tagId?: (string | null);
};

export type PreviewBulkContactsContactsBulkPreviewGetResponse = (ContactsPublic);

export type ListContactsContactsGetData = {
    groupId?: (string | null);
    ids?: (Array<(string)> | null);
    includeDeleted?: boolean;
    isArchived?: (boolean | null);
    isFavorite?: (boolean | null);
    limit?: number;
    onlyDeleted?: boolean;
    search?: (string | null);
    skip?: number;
    stage?: (string | null);
    tagId?: (string | null);
};

export type ListContactsContactsGetResponse = (ContactsPublic);

export type CreateContactContactsPostData = {
    requestBody: ContactCreate;
};

export type CreateContactContactsPostResponse = (ContactPublic);

export type ListLosingTouchContactsLosingTouchGetData = {
    limit?: number;
};

export type ListLosingTouchContactsLosingTouchGetResponse = (ContactsPublic);

export type GetContactContactsContactIdGetData = {
    contactId: string;
};

export type GetContactContactsContactIdGetResponse = (ContactPublic);

export type UpdateContactContactsContactIdPatchData = {
    contactId: string;
    requestBody: ContactUpdate;
};

export type UpdateContactContactsContactIdPatchResponse = (ContactPublic);

export type DeleteContactContactsContactIdDeleteData = {
    contactId: string;
};

export type DeleteContactContactsContactIdDeleteResponse = (unknown);

export type ListContactMentionsContactsContactIdMentionsGetData = {
    contactId: string;
};

export type ListContactMentionsContactsContactIdMentionsGetResponse = (Array<NoteMentionPublic>);

export type RestoreContactContactsContactIdRestorePostData = {
    contactId: string;
};

export type RestoreContactContactsContactIdRestorePostResponse = (ContactPublic);

export type ListFieldDefinitionsCustomFieldsDefinitionsGetResponse = (unknown);

export type CreateFieldDefinitionCustomFieldsDefinitionsPostData = {
    requestBody: CustomFieldDefinitionCreate;
};

export type CreateFieldDefinitionCustomFieldsDefinitionsPostResponse = (CustomFieldDefinitionPublic);

export type UpdateFieldDefinitionCustomFieldsDefinitionsDefIdPatchData = {
    defId: string;
    requestBody: CustomFieldDefinitionUpdate;
};

export type UpdateFieldDefinitionCustomFieldsDefinitionsDefIdPatchResponse = (CustomFieldDefinitionPublic);

export type DeleteFieldDefinitionCustomFieldsDefinitionsDefIdDeleteData = {
    defId: string;
};

export type DeleteFieldDefinitionCustomFieldsDefinitionsDefIdDeleteResponse = (unknown);

export type ListFieldValuesCustomFieldsValuesContactContactIdGetData = {
    contactId: string;
};

export type ListFieldValuesCustomFieldsValuesContactContactIdGetResponse = (unknown);

export type CreateFieldValueCustomFieldsValuesPostData = {
    requestBody: CustomFieldValueCreate;
};

export type CreateFieldValueCustomFieldsValuesPostResponse = (CustomFieldValuePublic);

export type UpdateFieldValueCustomFieldsValuesValueIdPatchData = {
    requestBody: CustomFieldValueUpdate;
    valueId: string;
};

export type UpdateFieldValueCustomFieldsValuesValueIdPatchResponse = (CustomFieldValuePublic);

export type DeleteFieldValueCustomFieldsValuesValueIdDeleteData = {
    valueId: string;
};

export type DeleteFieldValueCustomFieldsValuesValueIdDeleteResponse = (unknown);

export type ListDebtsDebtsContactContactIdGetData = {
    contactId: string;
};

export type ListDebtsDebtsContactContactIdGetResponse = (DebtsPublic);

export type CreateDebtRouteDebtsPostData = {
    requestBody: DebtCreate;
};

export type CreateDebtRouteDebtsPostResponse = (DebtPublic);

export type UpdateDebtDebtsDebtIdPatchData = {
    debtId: string;
    requestBody: DebtUpdate;
};

export type UpdateDebtDebtsDebtIdPatchResponse = (DebtPublic);

export type DeleteDebtDebtsDebtIdDeleteData = {
    debtId: string;
};

export type DeleteDebtDebtsDebtIdDeleteResponse = (unknown);

export type ListGiftsGiftsContactContactIdGetData = {
    contactId: string;
};

export type ListGiftsGiftsContactContactIdGetResponse = (GiftsPublic);

export type CreateGiftRouteGiftsPostData = {
    requestBody: GiftCreate;
};

export type CreateGiftRouteGiftsPostResponse = (GiftPublic);

export type UpdateGiftGiftsGiftIdPatchData = {
    giftId: string;
    requestBody: GiftUpdate;
};

export type UpdateGiftGiftsGiftIdPatchResponse = (GiftPublic);

export type DeleteGiftGiftsGiftIdDeleteData = {
    giftId: string;
};

export type DeleteGiftGiftsGiftIdDeleteResponse = (unknown);

export type ListGroupsGroupsGetData = {
    limit?: number;
    skip?: number;
};

export type ListGroupsGroupsGetResponse = (GroupsPublic);

export type CreateGroupRouteGroupsPostData = {
    requestBody: GroupCreate;
};

export type CreateGroupRouteGroupsPostResponse = (GroupPublic);

export type UpdateGroupGroupsGroupIdPatchData = {
    groupId: string;
    requestBody: GroupUpdate;
};

export type UpdateGroupGroupsGroupIdPatchResponse = (GroupPublic);

export type DeleteGroupGroupsGroupIdDeleteData = {
    groupId: string;
};

export type DeleteGroupGroupsGroupIdDeleteResponse = (unknown);

export type ImportVcardImportExportImportVcardPostData = {
    formData: Body_import_vcard_import_export_import_vcard_post;
};

export type ImportVcardImportExportImportVcardPostResponse = (unknown);

export type ExportVcardImportExportExportVcardGetResponse = (unknown);

export type ExportJsonImportExportExportJsonGetResponse = (unknown);

export type ListInteractionsInteractionsGetData = {
    contactId?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListInteractionsInteractionsGetResponse = (InteractionsPublic);

export type CreateInteractionRouteInteractionsPostData = {
    requestBody: InteractionCreate;
};

export type CreateInteractionRouteInteractionsPostResponse = (InteractionPublic);

export type UpdateInteractionInteractionsInteractionIdPatchData = {
    interactionId: string;
    requestBody: InteractionUpdate;
};

export type UpdateInteractionInteractionsInteractionIdPatchResponse = (InteractionPublic);

export type DeleteInteractionInteractionsInteractionIdDeleteData = {
    interactionId: string;
};

export type DeleteInteractionInteractionsInteractionIdDeleteResponse = (unknown);

export type ListJournalEntriesJournalGetData = {
    limit?: number;
    skip?: number;
};

export type ListJournalEntriesJournalGetResponse = (JournalEntriesPublic);

export type CreateJournalEntryRouteJournalPostData = {
    requestBody: JournalEntryCreate;
};

export type CreateJournalEntryRouteJournalPostResponse = (JournalEntryPublic);

export type UpdateJournalEntryJournalEntryIdPatchData = {
    entryId: string;
    requestBody: JournalEntryUpdate;
};

export type UpdateJournalEntryJournalEntryIdPatchResponse = (JournalEntryPublic);

export type DeleteJournalEntryJournalEntryIdDeleteData = {
    entryId: string;
};

export type DeleteJournalEntryJournalEntryIdDeleteResponse = (unknown);

export type ListLifeEventsLifeEventsContactContactIdGetData = {
    contactId: string;
};

export type ListLifeEventsLifeEventsContactContactIdGetResponse = (LifeEventsPublic);

export type CreateLifeEventRouteLifeEventsPostData = {
    requestBody: LifeEventCreate;
};

export type CreateLifeEventRouteLifeEventsPostResponse = (LifeEventPublic);

export type UpdateLifeEventLifeEventsEventIdPatchData = {
    eventId: string;
    requestBody: LifeEventUpdate;
};

export type UpdateLifeEventLifeEventsEventIdPatchResponse = (LifeEventPublic);

export type DeleteLifeEventLifeEventsEventIdDeleteData = {
    eventId: string;
};

export type DeleteLifeEventLifeEventsEventIdDeleteResponse = (unknown);

export type LoginAccessTokenLoginAccessTokenPostData = {
    formData: Body_login_access_token_login_access_token_post;
};

export type LoginAccessTokenLoginAccessTokenPostResponse = (Token);

export type TestTokenLoginTestTokenPostResponse = (UserPublic);

export type RecoverPasswordPasswordRecoveryEmailPostData = {
    email: string;
};

export type RecoverPasswordPasswordRecoveryEmailPostResponse = (Message);

export type ResetPasswordResetPasswordPostData = {
    requestBody: NewPassword;
};

export type ResetPasswordResetPasswordPostResponse = (Message);

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostData = {
    email: string;
};

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostResponse = (string);

export type ListMediaRecommendationsMediaRecommendationsContactContactIdGetData = {
    contactId: string;
};

export type ListMediaRecommendationsMediaRecommendationsContactContactIdGetResponse = (MediaRecommendationsPublic);

export type CreateMediaRecommendationRouteMediaRecommendationsPostData = {
    requestBody: MediaRecommendationCreate;
};

export type CreateMediaRecommendationRouteMediaRecommendationsPostResponse = (MediaRecommendationPublic);

export type UpdateMediaRecommendationMediaRecommendationsRecIdPatchData = {
    recId: string;
    requestBody: MediaRecommendationUpdate;
};

export type UpdateMediaRecommendationMediaRecommendationsRecIdPatchResponse = (MediaRecommendationPublic);

export type DeleteMediaRecommendationMediaRecommendationsRecIdDeleteData = {
    recId: string;
};

export type DeleteMediaRecommendationMediaRecommendationsRecIdDeleteResponse = (unknown);

export type ListNotesNotesContactContactIdGetData = {
    contactId: string;
    limit?: number;
    skip?: number;
};

export type ListNotesNotesContactContactIdGetResponse = (NotesPublic);

export type CreateNoteRouteNotesPostData = {
    requestBody: NoteCreate;
};

export type CreateNoteRouteNotesPostResponse = (NotePublic);

export type UpdateNoteRouteNotesNoteIdPatchData = {
    noteId: string;
    requestBody: NoteUpdate;
};

export type UpdateNoteRouteNotesNoteIdPatchResponse = (NotePublic);

export type DeleteNoteNotesNoteIdDeleteData = {
    noteId: string;
};

export type DeleteNoteNotesNoteIdDeleteResponse = (unknown);

export type ListPetsPetsContactContactIdGetData = {
    contactId: string;
};

export type ListPetsPetsContactContactIdGetResponse = (unknown);

export type CreatePetRoutePetsPostData = {
    requestBody: PetCreate;
};

export type CreatePetRoutePetsPostResponse = (PetPublic);

export type UpdatePetPetsPetIdPatchData = {
    petId: string;
    requestBody: PetUpdate;
};

export type UpdatePetPetsPetIdPatchResponse = (PetPublic);

export type DeletePetPetsPetIdDeleteData = {
    petId: string;
};

export type DeletePetPetsPetIdDeleteResponse = (unknown);

export type CreateUserPrivateUsersPostData = {
    requestBody: PrivateUserCreate;
};

export type CreateUserPrivateUsersPostResponse = (UserPublic);

export type LookupInverseRelationshipsInverseGetData = {
    type: string;
};

export type LookupInverseRelationshipsInverseGetResponse = ({
    [key: string]: (string | null);
});

export type ListRelationshipsRelationshipsContactContactIdGetData = {
    contactId: string;
};

export type ListRelationshipsRelationshipsContactContactIdGetResponse = (unknown);

export type CreateRelationshipRouteRelationshipsPostData = {
    requestBody: RelationshipCreate;
};

export type CreateRelationshipRouteRelationshipsPostResponse = (RelationshipPublic);

export type UpdateRelationshipRelationshipsRelIdPatchData = {
    relId: string;
    requestBody: RelationshipUpdate;
};

export type UpdateRelationshipRelationshipsRelIdPatchResponse = (RelationshipPublic);

export type DeleteRelationshipRelationshipsRelIdDeleteData = {
    relId: string;
};

export type DeleteRelationshipRelationshipsRelIdDeleteResponse = (unknown);

export type ListRemindersRemindersGetData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type ListRemindersRemindersGetResponse = (RemindersPublic);

export type CreateReminderRouteRemindersPostData = {
    requestBody: ReminderCreate;
};

export type CreateReminderRouteRemindersPostResponse = (ReminderPublic);

export type UpdateReminderRemindersReminderIdPatchData = {
    reminderId: string;
    requestBody: ReminderUpdate;
};

export type UpdateReminderRemindersReminderIdPatchResponse = (ReminderPublic);

export type DeleteReminderRemindersReminderIdDeleteData = {
    reminderId: string;
};

export type DeleteReminderRemindersReminderIdDeleteResponse = (unknown);

export type SnoozeReminderRemindersReminderIdSnoozePostData = {
    minutes?: number;
    reminderId: string;
};

export type SnoozeReminderRemindersReminderIdSnoozePostResponse = (unknown);

export type ListTagsTagsGetData = {
    limit?: number;
    skip?: number;
};

export type ListTagsTagsGetResponse = (TagsPublic);

export type CreateTagRouteTagsPostData = {
    requestBody: TagCreate;
};

export type CreateTagRouteTagsPostResponse = (TagPublic);

export type UpdateTagTagsTagIdPatchData = {
    requestBody: TagUpdate;
    tagId: string;
};

export type UpdateTagTagsTagIdPatchResponse = (TagPublic);

export type DeleteTagTagsTagIdDeleteData = {
    tagId: string;
};

export type DeleteTagTagsTagIdDeleteResponse = (unknown);

export type CreateTagShareTagSharesPostData = {
    requestBody: _ShareIn;
};

export type CreateTagShareTagSharesPostResponse = (TagSharePublic);

export type ListTagSharesTagSharesGetData = {
    tagId: string;
};

export type ListTagSharesTagSharesGetResponse = (TagSharesPublic);

export type DeleteTagShareTagSharesTagIdGranteeIdDeleteData = {
    granteeId: string;
    tagId: string;
};

export type DeleteTagShareTagSharesTagIdGranteeIdDeleteResponse = ({
    [key: string]: (string);
});

export type ReadUsersUsersGetData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersUsersGetResponse = (UsersPublic);

export type CreateUserUsersPostData = {
    requestBody: UserCreate;
};

export type CreateUserUsersPostResponse = (UserPublic);

export type ReadUserMeUsersMeGetResponse = (UserPublic);

export type DeleteUserMeUsersMeDeleteResponse = (Message);

export type UpdateUserMeUsersMePatchData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeUsersMePatchResponse = (UserPublic);

export type UpdatePasswordMeUsersMePasswordPatchData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeUsersMePasswordPatchResponse = (Message);

export type RegisterUserUsersSignupPostData = {
    requestBody: UserRegister;
};

export type RegisterUserUsersSignupPostResponse = (UserPublic);

export type ReadUserByIdUsersUserIdGetData = {
    userId: string;
};

export type ReadUserByIdUsersUserIdGetResponse = (UserPublic);

export type UpdateUserUsersUserIdPatchData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UpdateUserUsersUserIdPatchResponse = (UserPublic);

export type DeleteUserUsersUserIdDeleteData = {
    userId: string;
};

export type DeleteUserUsersUserIdDeleteResponse = (Message);

export type TestEmailUtilsTestEmailPostData = {
    emailTo: string;
};

export type TestEmailUtilsTestEmailPostResponse = (Message);

export type HealthCheckUtilsHealthCheckGetResponse = (boolean);

export type ListWebhooksWebhooksGetResponse = (unknown);

export type CreateWebhookWebhooksPostData = {
    requestBody: WebhookEndpointBase;
};

export type CreateWebhookWebhooksPostResponse = (unknown);

export type UpdateWebhookWebhooksWebhookIdPatchData = {
    requestBody: WebhookEndpointBase;
    webhookId: string;
};

export type UpdateWebhookWebhooksWebhookIdPatchResponse = (unknown);

export type DeleteWebhookWebhooksWebhookIdDeleteData = {
    webhookId: string;
};

export type DeleteWebhookWebhooksWebhookIdDeleteResponse = (unknown);

export type InboundWebhookWebhooksInboundApiKeyPostData = {
    apiKey: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type InboundWebhookWebhooksInboundApiKeyPostResponse = (unknown);