#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12"]
# ///
"""Deploy kindred to homelab. Generated by project-kit.

Delegates to ~/Documents/Homelab/apps/kindred/justfile.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import typer

HOMELAB_APP = "kindred"
HOMELAB_PATH = Path.home() / "Documents" / "Homelab" / "apps" / HOMELAB_APP

app = typer.Typer(add_completion=False)


def _tag() -> str:
    return subprocess.run(
        ["git", "describe", "--tags", "--abbrev=0"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()


@app.command()
def main(
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if not HOMELAB_PATH.is_dir():
        typer.echo(f"error: homelab app path missing: {HOMELAB_PATH}", err=True)
        raise typer.Exit(code=1)
    if status:
        subprocess.run(
            [
                "docker",
                "compose",
                "--env-file",
                ".env",
                "ps",
                "--format",
                "table {{.Name}}\t{{.Image}}\t{{.State}}\t{{.Status}}",
            ],
            cwd=HOMELAB_PATH,
            check=True,
        )
        return
    if rollback:
        # last-but-one tag
        tags = subprocess.run(
            ["git", "tag", "--sort=-creatordate"],
            check=True, capture_output=True, text=True,
        ).stdout.split()
        if len(tags) < 2:
            typer.echo("error: no previous tag to rollback to", err=True)
            raise typer.Exit(code=1)
        target_tag = tags[1]
    else:
        target_tag = _tag()
    if dry_run:
        typer.echo(f"[dry-run] would cd {HOMELAB_PATH} && just deploy {target_tag}")
        return
    import socket
    current_host = socket.gethostname().split(".")[0].lower()
    target_host = "ares"
    if current_host != target_host:
        typer.echo(f"deploying {HOMELAB_APP} tag={target_tag} env={env} on host {target_host} via SSH…")
        subprocess.run(["ssh", target_host, f"cd {HOMELAB_PATH} && just deploy {target_tag}"], check=True)
    else:
        typer.echo(f"deploying {HOMELAB_APP} tag={target_tag} env={env}…")
        subprocess.run(["just", "deploy", target_tag], cwd=HOMELAB_PATH, check=True)


if __name__ == "__main__":
    app()
