#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12"]
# ///
"""Publish a verified kindred release to GHCR. Generated by project-kit."""

from __future__ import annotations

import json
import re
import subprocess

import typer

IMAGES_JSON = r"""[{"build_args": {"VITE_API_URL": "${VITE_API_URL:-}"}, "context": ".", "dockerfile": "Dockerfile.prod", "name": "kindred", "registry": "ghcr.io/pike00"}]"""
IMAGES = json.loads(IMAGES_JSON)
SEMVER = re.compile(r"v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?")

app = typer.Typer(add_completion=False)


def _image_refs() -> list[str]:
    return [f"{image['registry']}/{image['name']}" for image in IMAGES]


def _release_tag(tag: str) -> str:
    if SEMVER.fullmatch(tag) is None:
        typer.echo("error: a SemVer release tag is required, for example v1.2.3", err=True)
        raise typer.Exit(code=1)
    return tag


@app.command()
def main(
    tag: str = typer.Option("", "--tag"),
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if status:
        for image in _image_refs():
            subprocess.run(["crane", "digest", f"{image}:latest"], check=False)
        return
    if rollback:
        typer.echo(
            "GHCR rollback is not automatic; deploy an explicitly verified release tag instead",
            err=True,
        )
        raise typer.Exit(code=1)
    release_tag = _release_tag(tag)
    if dry_run:
        typer.echo(
            f"[dry-run] would just build-image {release_tag} -> immutable tag + :latest "
            f"(env={env})"
        )
        return
    subprocess.run(["just", "build-image", release_tag], check=True)


if __name__ == "__main__":
    app()
