#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""project-kit doctor for kindred. Generated by project-kit.

Checks subsystem health for this adopter. Stdlib only.
"""

from __future__ import annotations

import re
import shlex
import shutil
import socket
import subprocess
import sys
from pathlib import Path, PurePosixPath

EXPECTED_JUST = [
    "_lib",
    "preview",
    "release",
    "test",
    "deploy",
    "build",
    "db",
    "setup",
    "docs",
    "clean",
]
RESOLVER_TIMEOUT_SECONDS = 45
COMPOSE_FILENAMES = ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml")


def _ok(msg: str) -> None:
    print(f"  ✓ {msg}")


def _warn(msg: str) -> None:
    print(f"  ⚠ {msg}")


def _fail(msg: str) -> None:
    print(f"  ✗ {msg}")


def _check_cmd(layer: str, cmd: str) -> int:
    """Resolve the test layer's runner on $PATH (no execution). Returns warn count.

    Strips leading `cd … &&` segments so the real runner is checked, not `cd`.
    A missing runner warns rather than fails — many adopters install tools into
    a project-local venv that isn't on $PATH at doctor time.
    """
    segment = cmd.split("&&")[-1].strip()
    runner = segment.split()[0] if segment.split() else ""
    if runner and shutil.which(runner):
        _ok(f"{layer} test runner on $PATH: {runner}")
        return 0
    _warn(f"{layer} test runner not on $PATH: {runner!r} (cmd: {cmd})")
    return 1


def _normalize_stack_selector(value: str, label: str) -> str:
    if not value or value.startswith("/") or not re.fullmatch(r"[A-Za-z0-9._/-]+", value):
        raise ValueError(f"unsafe {label}: {value!r}")
    path = PurePosixPath(value)
    if ".." in path.parts:
        raise ValueError(f"unsafe {label}: {value!r}")
    return path.as_posix().strip("/")


def _resolve_stack_output(output: str) -> str:
    """Validate a resolver base/stack pair and return the relative stack path."""
    lines = output.splitlines()
    if len(lines) != 1:
        raise ValueError("stack resolver output must contain exactly one line")
    parts = lines[0].split("\t")
    if len(parts) != 2 or not all(parts):
        raise ValueError(f"malformed stack resolver output: {lines[0]!r}")
    base, stack = parts
    base_path = PurePosixPath(base)
    stack_path = PurePosixPath(stack)
    if not base_path.is_absolute() or not stack_path.is_absolute():
        raise ValueError("stack resolver paths must be absolute")
    if base_path.as_posix() != base or stack_path.as_posix() != stack:
        raise ValueError("stack resolver paths must be canonical")
    try:
        relative = stack_path.relative_to(base_path)
    except ValueError as exc:
        raise ValueError("resolved stack is outside the Homelab root") from exc
    if relative == PurePosixPath("."):
        raise ValueError("resolved stack cannot be the Homelab root")
    return _normalize_stack_selector(relative.as_posix(), "resolved stack path")


def _remote_resolver_command(selector: str) -> str:
    quoted_selector = shlex.quote(selector)
    return (
        'base="$HOME/projects/Homelab"; '
        f'candidate="$base"/{quoted_selector}; '
        'if [ ! -f "$candidate/docker-compose.yml" ] '
        '&& [ ! -f "$candidate/docker-compose.yaml" ] '
        '&& [ ! -f "$candidate/compose.yml" ] '
        '&& [ ! -f "$candidate/compose.yaml" ]; then '
        'printf "canonical Homelab stack path not found: %s\\n" "$candidate" >&2; '
        "exit 2; fi; "
        'stack="$(HOMELAB_BASE_DIR="$base" '
        f'"$base/infra/scripts/resolve-stack.py" {quoted_selector})" || exit $?; '
        'printf "%s\\t%s\\n" "$base" "$stack"'
    )


def _stack_resolution(
    deploy_host: str,
    execution_host: str,
    ssh_alias: str,
    selector: str,
) -> str:
    homelab_root = Path.home() / "projects" / "Homelab"
    resolver = homelab_root / "infra" / "scripts" / "resolve-stack.py"
    if not deploy_host or execution_host == deploy_host:
        candidate = homelab_root / selector
        if not any((candidate / name).is_file() for name in COMPOSE_FILENAMES):
            raise RuntimeError(
                f"canonical Homelab stack path not found: {selector!r}; "
                "migrate homelab_app to the audited path relative to the Homelab root"
            )
        command = [
            "env",
            f"HOMELAB_BASE_DIR={homelab_root}",
            str(resolver),
            selector,
        ]
        cwd = homelab_root
    else:
        if not ssh_alias:
            raise RuntimeError(f"deploy host is {deploy_host!r}, but no SSH alias is configured")
        command = [
            "ssh",
            "-T",
            "-o",
            "BatchMode=yes",
            "-o",
            "ConnectTimeout=5",
            "-o",
            "ConnectionAttempts=1",
            ssh_alias,
            _remote_resolver_command(selector),
        ]
        cwd = None
    proc = subprocess.run(
        command,
        stdin=subprocess.DEVNULL,
        capture_output=True,
        text=True,
        cwd=cwd,
        timeout=RESOLVER_TIMEOUT_SECONDS,
        check=False,
        start_new_session=True,
    )
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).strip()[:160]
        raise RuntimeError(f"stack resolver command failed: {detail}")
    if not deploy_host or execution_host == deploy_host:
        return f"{homelab_root}\t{proc.stdout.strip()}\n"
    return proc.stdout


def main() -> int:
    repo = Path.cwd()
    print("project-kit doctor — kindred\n")
    print("configuration:")
    pk = repo / ".project-kit"
    if not pk.is_dir():
        _fail(".project-kit/ missing")
        return 2
    fails = 0
    warns = 0
    missing = [n for n in EXPECTED_JUST if not (pk / f"{n}.just").is_file()]
    if missing:
        _fail(f"missing .just files: {missing}")
        fails += 1
    else:
        _ok(f"all {len(EXPECTED_JUST)} .just files present")
    jf = repo / "justfile"
    if jf.is_file():
        text = jf.read_text()
        if "import '.project-kit/_lib.just'" in text:
            _ok("root justfile imports project-kit block")
        else:
            _fail("root justfile missing project-kit import block")
            fails += 1
        if shutil.which("just"):
            proc = subprocess.run(
                ["just", "--justfile", str(jf), "--summary"],
                capture_output=True,
                text=True,
                cwd=str(repo),
                check=False,
            )
            if proc.returncode == 0:
                _ok("root justfile parses (just --summary)")
            else:
                _fail("root justfile does not parse: " + (proc.stderr or proc.stdout).strip()[:120])
                fails += 1
        else:
            _warn("just not on $PATH; skipped justfile parse check")
            warns += 1
    else:
        _fail("root justfile missing")
        fails += 1

    print("\npreview:")
    compose_file = "compose.worktree.yml"
    if (repo / compose_file).is_file():
        _ok(f"{compose_file} present")
    else:
        _fail(f"{compose_file} missing")
        fails += 1
    print("\nrelease:")
    if (repo / ".project-kit" / "cliff.toml").is_file():
        _ok(".project-kit/cliff.toml present")
    else:
        _fail(".project-kit/cliff.toml missing")
        fails += 1
    if shutil.which("gh"):
        _ok("gh CLI available")
    else:
        _warn("gh CLI not on $PATH")
        warns += 1
    print("\ntest:")
    warns += _check_cmd("backend", "docker compose -f compose.dev.yml exec -T backend pytest")
    warns += _check_cmd("frontend", "cd frontend \u0026\u0026 pnpm run test")
    warns += _check_cmd("e2e", "bash scripts/run-e2e-prepush.sh")
    print("\ndeploy:")
    deploy_host = "".lower()
    execution_host = socket.gethostname().split(".", 1)[0].lower()
    ssh_alias = ""
    try:
        resolution = _stack_resolution(
            deploy_host,
            execution_host,
            ssh_alias,
            "kindred",
        )
        resolved_stack = _resolve_stack_output(resolution)
    except (FileNotFoundError, RuntimeError, subprocess.TimeoutExpired, ValueError) as exc:
        _fail(f"homelab stack resolution failed: {exc}")
        fails += 1
    else:
        _ok(f"homelab stack resolves to {resolved_stack}")
    print("\nbuild:")
    dockerfiles = [
        "Dockerfile.prod",
    ]
    missing_dockerfiles = [path for path in dockerfiles if not (repo / path).is_file()]
    if not dockerfiles:
        _fail("no container images configured")
        fails += 1
    elif missing_dockerfiles:
        _fail(f"configured Dockerfiles missing: {missing_dockerfiles}")
        fails += 1
    else:
        _ok(f"configured Dockerfiles present: {dockerfiles}")
    try:
        subprocess.run(["docker", "info"], check=True, capture_output=True, timeout=5)
        _ok("docker daemon reachable")
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        _warn("docker daemon not reachable")
        warns += 1

    print(f"\n{fails} failures, {warns} warnings.")
    if fails:
        return 2
    if warns:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
