#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""project-kit doctor for kindred. Generated by project-kit.

Checks subsystem health for this adopter. Stdlib only.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

EXPECTED_JUST = [
    "_lib", "preview", "release", "test", "deploy",
    "build", "db", "setup", "docs", "clean",
]


def _ok(msg: str) -> None:
    print(f"  ✓ {msg}")


def _warn(msg: str) -> None:
    print(f"  ⚠ {msg}")


def _fail(msg: str) -> None:
    print(f"  ✗ {msg}")


def _check_cmd(layer: str, cmd: str) -> int:
    """Resolve the test layer's runner on $PATH (no execution). Returns warn count.

    Strips leading `cd … &&` segments so the real runner is checked, not `cd`.
    A missing runner warns rather than fails — many adopters install tools into
    a project-local venv that isn't on $PATH at doctor time.
    """
    segment = cmd.split("&&")[-1].strip()
    runner = segment.split()[0] if segment.split() else ""
    if runner and shutil.which(runner):
        _ok(f"{layer} test runner on $PATH: {runner}")
        return 0
    _warn(f"{layer} test runner not on $PATH: {runner!r} (cmd: {cmd})")
    return 1


def main() -> int:
    repo = Path.cwd()
    print(f"project-kit doctor — kindred\n")
    print("configuration:")
    pk = repo / ".project-kit"
    if not pk.is_dir():
        _fail(".project-kit/ missing")
        return 2
    fails = 0
    warns = 0
    missing = [n for n in EXPECTED_JUST if not (pk / f"{n}.just").is_file()]
    if missing:
        _fail(f"missing .just files: {missing}")
        fails += 1
    else:
        _ok(f"all {len(EXPECTED_JUST)} .just files present")
    jf = repo / "justfile"
    if jf.is_file():
        text = jf.read_text()
        if "import '.project-kit/_lib.just'" in text:
            _ok("root justfile imports project-kit block")
        else:
            _fail("root justfile missing project-kit import block")
            fails += 1
        if shutil.which("just"):
            proc = subprocess.run(
                ["just", "--justfile", str(jf), "--summary"],
                capture_output=True, text=True, cwd=str(repo),
            )
            if proc.returncode == 0:
                _ok("root justfile parses (just --summary)")
            else:
                _fail("root justfile does not parse: " + (proc.stderr or proc.stdout).strip()[:120])
                fails += 1
        else:
            _warn("just not on $PATH; skipped justfile parse check")
            warns += 1
    else:
        _fail("root justfile missing")
        fails += 1

    print("\npreview:")
    if (repo / "compose.dev.yml").is_file():
        _ok("compose.dev.yml present")
    else:
        _fail("compose.dev.yml missing")
        fails += 1
    print("\nrelease:")
    if (repo / ".project-kit" / "cliff.toml").is_file():
        _ok(".project-kit/cliff.toml present")
    else:
        _fail(".project-kit/cliff.toml missing")
        fails += 1
    if shutil.which("gh"):
        _ok("gh CLI available")
    else:
        _warn("gh CLI not on $PATH")
        warns += 1
    print("\ntest:")
    warns += _check_cmd("backend", "docker compose -f compose.dev.yml exec -T backend pytest")
    warns += _check_cmd("frontend", "cd frontend \u0026\u0026 pnpm run test")
    warns += _check_cmd("e2e", "bash scripts/run-e2e-prepush.sh")
    print("\ndeploy:")
    homelab_app = Path.home() / "Documents" / "Homelab" / "apps" / "kindred"
    if homelab_app.is_dir():
        _ok(f"homelab app at {homelab_app}")
    else:
        _fail(f"homelab app dir missing: {homelab_app}")
        fails += 1
    print("\nbuild:")
    dfs = [n for n in ("Dockerfile", "Dockerfile.prod") if (repo / n).is_file()]
    if dfs:
        _ok(f"Dockerfile present: {dfs}")
    else:
        _fail("no Dockerfile")
        fails += 1
    try:
        subprocess.run(["docker", "info"], check=True, capture_output=True, timeout=5)
        _ok("docker daemon reachable")
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        _warn("docker daemon not reachable")
        warns += 1

    print(f"\n{fails} failures, {warns} warnings.")
    if fails:
        return 2
    if warns:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
