"""Add calendar_token table.

Revision ID: add_calendar_token
Revises: fe56fa70289e
Create Date: 2026-05-02
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel, Field
import uuid

# revision identifiers, used by Alembic.
revision = "add_calendar_token"
down_revision = "fe56fa70289e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "calendar_token",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False, primary_key=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False, unique=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="active"),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.Index("ix_calendar_token_token", "token", unique=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table("calendar_token")
    # ### end Alembic commands ###
