/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTagsRouteImport } from './routes/_layout/tags'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRemindersRouteImport } from './routes/_layout/reminders'
import { Route as LayoutJournalRouteImport } from './routes/_layout/journal'
import { Route as LayoutInteractionsRouteImport } from './routes/_layout/interactions'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutContactsRouteImport } from './routes/_layout/contacts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutContactsIndexRouteImport } from './routes/_layout/contacts/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutContactsContactIdRouteImport } from './routes/_layout/contacts/$contactId'
import { Route as LayoutAdminWebhooksRouteImport } from './routes/_layout/admin/webhooks'
import { Route as LayoutAdminImportExportRouteImport } from './routes/_layout/admin/import-export'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTagsRoute = LayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRemindersRoute = LayoutRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJournalRoute = LayoutJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInteractionsRoute = LayoutInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactsRoute = LayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactsIndexRoute = LayoutContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutContactsRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutContactsContactIdRoute = LayoutContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => LayoutContactsRoute,
} as any)
const LayoutAdminWebhooksRoute = LayoutAdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminImportExportRoute = LayoutAdminImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/contacts': typeof LayoutContactsRouteWithChildren
  '/groups': typeof LayoutGroupsRoute
  '/interactions': typeof LayoutInteractionsRoute
  '/journal': typeof LayoutJournalRoute
  '/reminders': typeof LayoutRemindersRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/admin/import-export': typeof LayoutAdminImportExportRoute
  '/admin/webhooks': typeof LayoutAdminWebhooksRoute
  '/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/contacts/': typeof LayoutContactsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/groups': typeof LayoutGroupsRoute
  '/interactions': typeof LayoutInteractionsRoute
  '/journal': typeof LayoutJournalRoute
  '/reminders': typeof LayoutRemindersRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/': typeof LayoutIndexRoute
  '/admin/import-export': typeof LayoutAdminImportExportRoute
  '/admin/webhooks': typeof LayoutAdminWebhooksRoute
  '/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/contacts': typeof LayoutContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/contacts': typeof LayoutContactsRouteWithChildren
  '/_layout/groups': typeof LayoutGroupsRoute
  '/_layout/interactions': typeof LayoutInteractionsRoute
  '/_layout/journal': typeof LayoutJournalRoute
  '/_layout/reminders': typeof LayoutRemindersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tags': typeof LayoutTagsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/import-export': typeof LayoutAdminImportExportRoute
  '/_layout/admin/webhooks': typeof LayoutAdminWebhooksRoute
  '/_layout/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/contacts/': typeof LayoutContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/contacts'
    | '/groups'
    | '/interactions'
    | '/journal'
    | '/reminders'
    | '/settings'
    | '/tags'
    | '/admin/import-export'
    | '/admin/webhooks'
    | '/contacts/$contactId'
    | '/admin/'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/groups'
    | '/interactions'
    | '/journal'
    | '/reminders'
    | '/settings'
    | '/tags'
    | '/'
    | '/admin/import-export'
    | '/admin/webhooks'
    | '/contacts/$contactId'
    | '/admin'
    | '/contacts'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/contacts'
    | '/_layout/groups'
    | '/_layout/interactions'
    | '/_layout/journal'
    | '/_layout/reminders'
    | '/_layout/settings'
    | '/_layout/tags'
    | '/_layout/'
    | '/_layout/admin/import-export'
    | '/_layout/admin/webhooks'
    | '/_layout/contacts/$contactId'
    | '/_layout/admin/'
    | '/_layout/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tags': {
      id: '/_layout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutTagsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reminders': {
      id: '/_layout/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof LayoutRemindersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journal': {
      id: '/_layout/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof LayoutJournalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interactions': {
      id: '/_layout/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof LayoutInteractionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts': {
      id: '/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutContactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts/': {
      id: '/_layout/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof LayoutContactsIndexRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/contacts/$contactId': {
      id: '/_layout/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof LayoutContactsContactIdRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/admin/webhooks': {
      id: '/_layout/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof LayoutAdminWebhooksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/import-export': {
      id: '/_layout/admin/import-export'
      path: '/import-export'
      fullPath: '/admin/import-export'
      preLoaderRoute: typeof LayoutAdminImportExportRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminImportExportRoute: typeof LayoutAdminImportExportRoute
  LayoutAdminWebhooksRoute: typeof LayoutAdminWebhooksRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminImportExportRoute: LayoutAdminImportExportRoute,
  LayoutAdminWebhooksRoute: LayoutAdminWebhooksRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutContactsRouteChildren {
  LayoutContactsContactIdRoute: typeof LayoutContactsContactIdRoute
  LayoutContactsIndexRoute: typeof LayoutContactsIndexRoute
}

const LayoutContactsRouteChildren: LayoutContactsRouteChildren = {
  LayoutContactsContactIdRoute: LayoutContactsContactIdRoute,
  LayoutContactsIndexRoute: LayoutContactsIndexRoute,
}

const LayoutContactsRouteWithChildren = LayoutContactsRoute._addFileChildren(
  LayoutContactsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutContactsRoute: typeof LayoutContactsRouteWithChildren
  LayoutGroupsRoute: typeof LayoutGroupsRoute
  LayoutInteractionsRoute: typeof LayoutInteractionsRoute
  LayoutJournalRoute: typeof LayoutJournalRoute
  LayoutRemindersRoute: typeof LayoutRemindersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTagsRoute: typeof LayoutTagsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutContactsRoute: LayoutContactsRouteWithChildren,
  LayoutGroupsRoute: LayoutGroupsRoute,
  LayoutInteractionsRoute: LayoutInteractionsRoute,
  LayoutJournalRoute: LayoutJournalRoute,
  LayoutRemindersRoute: LayoutRemindersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTagsRoute: LayoutTagsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
