/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTagsRouteImport } from './routes/_layout/tags'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRemindersRouteImport } from './routes/_layout/reminders'
import { Route as LayoutJournalRouteImport } from './routes/_layout/journal'
import { Route as LayoutInteractionsRouteImport } from './routes/_layout/interactions'
import { Route as LayoutGraphRouteImport } from './routes/_layout/graph'
import { Route as LayoutContactsRouteImport } from './routes/_layout/contacts'
import { Route as LayoutCalendarRouteImport } from './routes/_layout/calendar'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutContactsIndexRouteImport } from './routes/_layout/contacts/index'
import { Route as LayoutContactsKanbanRouteImport } from './routes/_layout/contacts/kanban'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutGiftsKanbanRouteImport } from './routes/_layout/gifts/kanban'
import { Route as LayoutContactsMapRouteImport } from './routes/_layout/contacts/map'
import { Route as LayoutContactsKanbanRouteImport } from './routes/_layout/contacts/kanban'
import { Route as LayoutContactsContactIdRouteImport } from './routes/_layout/contacts/$contactId'
import { Route as LayoutAdminWebhooksRouteImport } from './routes/_layout/admin/webhooks'
import { Route as LayoutAdminVcardConflictsRouteImport } from './routes/_layout/admin/vcard-conflicts'
import { Route as LayoutAdminImportExportRouteImport } from './routes/_layout/admin/import-export'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTagsRoute = LayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRemindersRoute = LayoutRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJournalRoute = LayoutJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInteractionsRoute = LayoutInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContactsRoute = LayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCalendarRoute = LayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContactsIndexRoute = LayoutContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutContactsRoute,
} as any)

const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)

const LayoutContactsContactIdRoute = LayoutContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => LayoutContactsRoute,
} as any)

const LayoutContactsKanbanRoute = LayoutContactsKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => LayoutContactsRoute,
} as any)

const LayoutAdminWebhooksRoute = LayoutAdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => LayoutAdminRoute,
} as any)

const LayoutAdminImportExportRoute = LayoutAdminImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/calendar': typeof LayoutCalendarRoute
  '/contacts': typeof LayoutContactsRouteWithChildren
  '/graph': typeof LayoutGraphRoute
  '/interactions': typeof LayoutInteractionsRoute
  '/journal': typeof LayoutJournalRoute
  '/reminders': typeof LayoutRemindersRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/admin/import-export': typeof LayoutAdminImportExportRoute
  '/admin/vcard-conflicts': typeof LayoutAdminVcardConflictsRoute
  '/admin/webhooks': typeof LayoutAdminWebhooksRoute
  '/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/contacts/kanban': typeof LayoutContactsKanbanRoute
  '/contacts/map': typeof LayoutContactsMapRoute
  '/gifts/kanban': typeof LayoutGiftsKanbanRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/contacts/': typeof LayoutContactsIndexRoute
  '/contacts/kanban': typeof LayoutContactsKanbanRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof LayoutCalendarRoute
  '/graph': typeof LayoutGraphRoute
  '/interactions': typeof LayoutInteractionsRoute
  '/journal': typeof LayoutJournalRoute
  '/reminders': typeof LayoutRemindersRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/': typeof LayoutIndexRoute
  '/admin/import-export': typeof LayoutAdminImportExportRoute
  '/admin/vcard-conflicts': typeof LayoutAdminVcardConflictsRoute
  '/admin/webhooks': typeof LayoutAdminWebhooksRoute
  '/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/contacts/kanban': typeof LayoutContactsKanbanRoute
  '/contacts/map': typeof LayoutContactsMapRoute
  '/gifts/kanban': typeof LayoutGiftsKanbanRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/contacts': typeof LayoutContactsIndexRoute
  '/contacts/kanban': typeof LayoutContactsKanbanRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/calendar': typeof LayoutCalendarRoute
  '/_layout/contacts': typeof LayoutContactsRouteWithChildren
  '/_layout/graph': typeof LayoutGraphRoute
  '/_layout/interactions': typeof LayoutInteractionsRoute
  '/_layout/journal': typeof LayoutJournalRoute
  '/_layout/reminders': typeof LayoutRemindersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tags': typeof LayoutTagsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/import-export': typeof LayoutAdminImportExportRoute
  '/_layout/admin/vcard-conflicts': typeof LayoutAdminVcardConflictsRoute
  '/_layout/admin/webhooks': typeof LayoutAdminWebhooksRoute
  '/_layout/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/_layout/contacts/kanban': typeof LayoutContactsKanbanRoute
  '/_layout/contacts/map': typeof LayoutContactsMapRoute
  '/_layout/gifts/kanban': typeof LayoutGiftsKanbanRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/contacts/': typeof LayoutContactsIndexRoute
  '/_layout/contacts/kanban': typeof LayoutContactsKanbanRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/calendar'
    | '/contacts'
    | '/graph'
    | '/interactions'
    | '/journal'
    | '/reminders'
    | '/settings'
    | '/tags'
    | '/admin/import-export'
    | '/admin/vcard-conflicts'
    | '/admin/webhooks'
    | '/contacts/$contactId'
    | '/contacts/kanban'
    | '/contacts/map'
    | '/gifts/kanban'
    | '/admin/'
    | '/contacts/'
    | '/contacts/kanban'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/graph'
    | '/interactions'
    | '/journal'
    | '/reminders'
    | '/settings'
    | '/tags'
    | '/'
    | '/admin/import-export'
    | '/admin/vcard-conflicts'
    | '/admin/webhooks'
    | '/contacts/$contactId'
    | '/contacts/kanban'
    | '/contacts/map'
    | '/gifts/kanban'
    | '/admin'
    | '/contacts'
    | '/contacts/kanban'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/calendar'
    | '/_layout/contacts'
    | '/_layout/graph'
    | '/_layout/interactions'
    | '/_layout/journal'
    | '/_layout/reminders'
    | '/_layout/settings'
    | '/_layout/tags'
    | '/_layout/'
    | '/_layout/admin/import-export'
    | '/_layout/admin/vcard-conflicts'
    | '/_layout/admin/webhooks'
    | '/_layout/contacts/$contactId'
    | '/_layout/contacts/kanban'
    | '/_layout/contacts/map'
    | '/_layout/gifts/kanban'
    | '/_layout/admin/'
    | '/_layout/contacts/'
    | '/_layout/contacts/kanban'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tags': {
      id: '/_layout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutTagsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reminders': {
      id: '/_layout/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof LayoutRemindersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journal': {
      id: '/_layout/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof LayoutJournalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interactions': {
      id: '/_layout/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof LayoutInteractionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/graph': {
      id: '/_layout/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof LayoutGraphRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts': {
      id: '/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutContactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar': {
      id: '/_layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LayoutCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts/': {
      id: '/_layout/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof LayoutContactsIndexRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/contacts/kanban': {
      id: '/_layout/contacts/kanban'
      path: '/kanban'
      fullPath: '/contacts/kanban'
      preLoaderRoute: typeof LayoutContactsKanbanRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/gifts/kanban': {
      id: '/_layout/gifts/kanban'
      path: '/gifts/kanban'
      fullPath: '/gifts/kanban'
      preLoaderRoute: typeof LayoutGiftsKanbanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts/map': {
      id: '/_layout/contacts/map'
      path: '/map'
      fullPath: '/contacts/map'
      preLoaderRoute: typeof LayoutContactsMapRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/contacts/kanban': {
      id: '/_layout/contacts/kanban'
      path: '/kanban'
      fullPath: '/contacts/kanban'
      preLoaderRoute: typeof LayoutContactsKanbanRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/contacts/$contactId': {
      id: '/_layout/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof LayoutContactsContactIdRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/admin/webhooks': {
      id: '/_layout/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof LayoutAdminWebhooksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/vcard-conflicts': {
      id: '/_layout/admin/vcard-conflicts'
      path: '/vcard-conflicts'
      fullPath: '/admin/vcard-conflicts'
      preLoaderRoute: typeof LayoutAdminVcardConflictsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/import-export': {
      id: '/_layout/admin/import-export'
      path: '/import-export'
      fullPath: '/admin/import-export'
      preLoaderRoute: typeof LayoutAdminImportExportRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminImportExportRoute: typeof LayoutAdminImportExportRoute
  LayoutAdminVcardConflictsRoute: typeof LayoutAdminVcardConflictsRoute
  LayoutAdminWebhooksRoute: typeof LayoutAdminWebhooksRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminImportExportRoute: LayoutAdminImportExportRoute,
  LayoutAdminVcardConflictsRoute: LayoutAdminVcardConflictsRoute,
  LayoutAdminWebhooksRoute: LayoutAdminWebhooksRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutContactsRouteChildren {
  LayoutContactsContactIdRoute: typeof LayoutContactsContactIdRoute
  LayoutContactsKanbanRoute: typeof LayoutContactsKanbanRoute
  LayoutContactsMapRoute: typeof LayoutContactsMapRoute
  LayoutContactsIndexRoute: typeof LayoutContactsIndexRoute
  LayoutContactsKanbanRoute: typeof LayoutContactsKanbanRoute
}

const LayoutContactsRouteChildren: LayoutContactsRouteChildren = {
  LayoutContactsContactIdRoute: LayoutContactsContactIdRoute,
  LayoutContactsKanbanRoute: LayoutContactsKanbanRoute,
  LayoutContactsMapRoute: LayoutContactsMapRoute,
  LayoutContactsIndexRoute: LayoutContactsIndexRoute,
  LayoutContactsKanbanRoute: LayoutContactsKanbanRoute,
}

const LayoutContactsRouteWithChildren = LayoutContactsRoute._addFileChildren(
  LayoutContactsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutCalendarRoute: typeof LayoutCalendarRoute
  LayoutContactsRoute: typeof LayoutContactsRouteWithChildren
  LayoutGraphRoute: typeof LayoutGraphRoute
  LayoutInteractionsRoute: typeof LayoutInteractionsRoute
  LayoutJournalRoute: typeof LayoutJournalRoute
  LayoutRemindersRoute: typeof LayoutRemindersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTagsRoute: typeof LayoutTagsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGiftsKanbanRoute: typeof LayoutGiftsKanbanRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutCalendarRoute: LayoutCalendarRoute,
  LayoutContactsRoute: LayoutContactsRouteWithChildren,
  LayoutGraphRoute: LayoutGraphRoute,
  LayoutInteractionsRoute: LayoutInteractionsRoute,
  LayoutJournalRoute: LayoutJournalRoute,
  LayoutRemindersRoute: LayoutRemindersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTagsRoute: LayoutTagsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGiftsKanbanRoute: LayoutGiftsKanbanRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
