/**
 * Single re-export module for every lucide icon used in the app.
 * Components MUST import icons from `@/lib/icons`, not directly from `lucide-react`,
 * so future renames or library swaps happen in one place.
 */

export type { LucideIcon } from "lucide-react"
// Additional icons for bulk operations
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  AtSign,
  Bell,
  BellOff,
  Building2,
  // Contact meta
  Cake,
  Calendar,
  CalendarHeart,
  Camera,
  Check,
  // Forms / inputs
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  // Pagination
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleCheck,
  Clock,
  Coffee,
  Crop,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileSpreadsheet,
  Film,
  Focus,
  Gift,
  GripVertical,
  HeartHandshake,
  // Sidebar nav
  Home,
  Info,
  Link,
  ListFilter,
  ListPlus,
  Loader2,
  // Misc
  LogOut,
  // Contact field types
  Mail,
  Map,
  Globe,
  // Card section icons
  MapPin,
  MessageSquare,
  // Interaction channels

  // FAB / Quick actions
  MessageSquarePlus,
  MessageSquareText,
  MessagesSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  // Action icons (monochrome, inherit text color)
  MoreHorizontal,
  NotebookPen,
  OctagonX,
  Package,
  PanelLeft,
  PawPrint,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SkipForward,
  Square,
  Star,
  // Theme
  Sun,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  UserRoundSearch,
  Users,
  UsersRound,
  Video,
  WifiOff,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react"
